### ISSUE TITLE
Discussion topic: Should we provide git in the default base box for Python?

### ISSUE THREAD

**Issue by paulproteus** [sandstorm-io/vagrant-spk#119]
Yesterday @phildini and I were working on a Python package, and his app's `requirements.txt` listed a dependency pinned to a specific git commit.

Eventually the `pip install -r requirements.txt` failed with an error that `git` could not be found.

So I wanted to raise this discussion topic: Should we provide git in the default (or perhaps just `uwsgi`) base box?

- Upside: `pip install` (which we do automatically run on behalf of the user) would work more frequently.

- Downside: The box would take longer to set up.

I gently vote for yes, but I wanted to get @zarvox 's opinion on this.

**Comment by zarvox** [comment]
Sure, that sounds fine.  We're already installing a bunch of other stuff, git's packages are actually pretty small, and Debian packages are cacheable with `apt-cacher-ng`.

I'd be in favor of including this anywhere people are likely to use git (possibly transitively) in their `build.sh`.
