### ISSUE TITLE
vagrant-spk should document a list of supported stacks

### ISSUE THREAD

**Issue by zarvox** [sandstorm-io/vagrant-spk#12]
Right now it's not very discoverable what stacks exist and what they include.  If we want people to use these stacks, we should make them more visible.

**Comment by JamborJan** [comment]
Agree, let me know if I can support you here by testing and writing stuff. Simply throw some lines at me what you would like to see here.

**Comment by elimisteve** [comment]
+1. I had to remember from the docs that "diy" is what I wanted, though that isn't a huge problem.

**Comment by paulproteus** [comment]
We do have this list in the docs:

- https://docs.sandstorm.io/en/latest/vagrant-spk/platform-stacks/

Is there a better place I can add it, so that people are more likely to see it? Honest question!
