### ISSUE TITLE
apt-get install lines should attempt to 'apt-get update' in the case of failure

### ISSUE THREAD

**Issue by paulproteus** [sandstorm-io/vagrant-spk#121]
@dwrensha hit this recently.

**Comment by zarvox** [comment]
Or they should just always `apt-get update` before `apt-get install`.

**Comment by paulproteus** [comment]
Yeah, I just vaguely hate making a no-op expensive.

**Comment by zarvox** [comment]
`setup.sh` is only run when the vm is first brought up (or you're explicitly running vagrant provision?), and if you have a fresh package list cache, you'll get Not Modified from the apt repos, so it's not super expensive either way.

And the rest of our stacks already do `apt-get update` before `apt-get install` everywhere, I believe.

**Comment by paulproteus** [comment]
+1 many thanks!​
