### ISSUE TITLE
Provide windows packages

### ISSUE THREAD

**Issue by zarvox** [sandstorm-io/vagrant-spk#13]
Most Windows users probably don't have a Python installation running around, so we should package `vagrant-spk` into either a single-file `vagrant-spk.exe` which embeds a python interpreter and can run cleanly, or an installer bundle (`.msi`?).

I gently prefer the former, since it means there's one less install step for end users.

Possible tools:
  * http://www.py2exe.org/ for standalone program
  * https://pynsist.readthedocs.org/en/latest/ for installers

**Comment by paulproteus** [comment]
FWIW I'm -0 on "just provide an EXE" because it has the downside that it
won't be on %PATH%, so I'm +1 on e.g. pynsist if it adjusts %PATH%
accordingly.​

I'm excited about all of this, though.

**Comment by zarvox** [comment]
"Tell the user to put vagrant-spk.exe in c:\windows\system32" is probably the wrong answer to that? ;)

I suppose PATH adjustments are probably important.  I'll probably have to read up on how to do that with NSIS; from what I can tell, that's unlikely to be supported directly by pynsist.

We should check on if Vagrant also adds itself to PATH.

**Comment by paulproteus** [comment]
FWIW nsis does have path magic. I think I remember using it in like 2004.

**Comment by paulproteus** [comment]
This issue is happily fixed. Marking as such.
