### ISSUE TITLE
Improve networking speed

### ISSUE THREAD

**Issue by paulproteus** [sandstorm-io/vagrant-spk#132]
@synchrone noticed on IRC today that uploading to one's `vagrant-spk` base box can be very slow. In my manual testing this morning, on Debian, I reproduced the slowness and I also tried manually changing the network adapter type to `virtio` within the VirtualBox GUI. This massively improved network speed.

I'm going to try some experiments before suggesting a specific course of action.

**Comment by paulproteus** [comment]
I'm on Debian. Test setup:

```
➜  ~  dd if=/dev/urandom bs=1M count=20 of=/tmp/20mb.bin
20+0 records in
20+0 records out
20971520 bytes (21 MB) copied, 1.57912 s, 13.3 MB/s
```

Test:

```
$ (cd .sandstorm; cat /tmp/20mb.bin | pv | vagrant ssh -c 'cat > /dev/null' )
```

- Set adapter to "PCnet-FAST III" in the VirtualBox GUI. Get this output from test.

```
➜  gmg-tester git:(master) ✗ (cd .sandstorm; cat /tmp/20mb.bin | pv | vagrant ssh -c 'cat > /dev/null' )
  20MiB 0:00:02 [9.72MiB/s] [     <=>                                                                                             ]
```

- Set adapter to "PCnet-FAST II" in VirtualBox GUI. Get this output from test.

```
  20MiB 0:00:02 [9.54MiB/s] [      <=>                                                                                                     ]
```

- Set adapter to "Intel PRO/1000 MT Desktop" in VirtualBox GUI. Get this output from test.

```
➜  gmg-tester git:(master) ✗ (cd .sandstorm; cat /tmp/20mb.bin | pv | vagrant ssh -c 'cat > /dev/null' )
  20MiB 0:00:02 [9.83MiB/s] [      <=>                                                                                                     ]
```

- Set adapter to "Intel PRO/1000 T Server" in VirtualBox GUI. Get this output from test.

```
➜  gmg-tester git:(master) ✗ (cd .sandstorm; cat /tmp/20mb.bin | pv | vagrant ssh -c 'cat > /dev/null' )
  20MiB 0:00:02 [9.96MiB/s] [      <=>                                                                                                     ]
```

- Set adapter to "Intel PRO/1000 MT Server" in VirtualBox GUI. Get this output from test.

```
➜  gmg-tester git:(master) ✗ (cd .sandstorm; cat /tmp/20mb.bin | pv | vagrant ssh -c 'cat > /dev/null' )
  20MiB 0:00:02 [9.58MiB/s] [      <=>                                                                                                     ]
```

- Set adapter to "Paravirtualized Network (virtio-net)" in VirtualBox GUI. Get this output from test.

```
➜  gmg-tester git:(master) ✗ (cd .sandstorm; cat /tmp/20mb.bin | pv | vagrant ssh -c 'cat > /dev/null' )
  20MiB 0:00:03 [6.59MiB/s] [       <=>                                                                                      ]
```

... OK I guess my test was not a useful test. That's frustrating to know. Hmm.

**Comment by paulproteus** [comment]
In qualitative manual testing, PCNet-Fast III "feels faster", even though the default network interface "feels slow" when uploading an SPK.

**Comment by paulproteus** [comment]
It does seem to me if we use PCNet-Fast III rather than the default (...what is the default...?) then we'll be in better shape. But these results gently suggest that maybe a reboot also helps, which is frustrating if true, since it makes testing it more difficult.

**Comment by paulproteus** [comment]
Possibly useful reading: https://github.com/hashbangcode/vlad/issues/200

**Comment by synchrone** [comment]
> ...what is the default...?

On my very default xubuntu 15.10, vagrant sets virtualbox adapter to "Intel PRO/1000 MT Desktop (NAT)". Changing to PCNet-Fast III does help indeed.

For virtualbox (but not other vagrant backends) this could be done easily enough:
```ruby
config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--nictype1", "Am79C973"]
end
```

**Comment by paulproteus** [comment]
> For virtualbox (but not other vagrant backends) this could be done easily
enough:

That's great, and for now, that workaround is good. Perhaps we should make
this the default for the VirtualBox VMs that we create. Doing some Googling
suggests this is sane, especially on multiple-CPU Vagrant VMs. Also note
that we're creating (on my laptop) an 8-CPU guest, not a 4-CPU guest. I
have 4 CPUs with Hyperthreading, so we end up miscounting them as 8. I
wonder if the performance problems are some fascinating problem that arises
from having too many CPUs allocated to the VM, with the VM not realizing
they're hyperthreaded.

For non-VirtualBox, I'm sure they'll have their own weird issues, so IMHO
this issue is only about VirtualBox.

**Comment by paulproteus** [comment]
Confirmed that this fix improves network speed on VirtualBox on Mac OS. I'll make the change shortly, since it seems harmless enough, and no one seems to object.
