### ISSUE TITLE
Idea: stop whitelisting Vagrant commands

### ISSUE THREAD

**Issue by paulproteus** [sandstorm-io/vagrant-spk#138]
As far as I can tell, there are two reasons we whitelist Vagrant commands:
- We require a `--` to separate `vagrant` command arguments from `vagrant-spk` command arguments, and
- We modify the behavior of some commands, such as `vagrant-spk up`.

I _think_ the only reason we require the `--` is that we support a `--work-directory` parameter. If we dropped that (which I have personally never used), and/or accepted that parameter as an environment variable, then we could stop whitelisting commands entirely.

@zarvox curious what you think. Implementing this isn't necessarily urgent, but I'm interested in seeing if we can come to an agreement on this. If this change would result in a cleaner design, then it's nice to have a decision so that either of us can feel free to implement it whenever we feel like it.

Context:

https://github.com/sandstorm-io/vagrant-spk/issues/118 is an issue that remained open for a while, and I want to propose a more general fix that allows us to be more responsive.

**Comment by paulproteus** [comment]
If we can stop modifying argv, then we can also make life easier for experienced vagrant users in another way. Right now, we ignore any argv we don't understand, but perhaps we can pass it through unmodified to the vagrant command we are proxying.

**Comment by zarvox** [comment]
There was some discussion, culminating in this mailinglist post: https://groups.google.com/forum/#!topic/sandstorm-dev/cuSNJ3IsP6I

Short story: we agreed to isolate vagrant-specific wrapper commands under a `vm` subcommand, which will do the existing sanity checks, but then will pass all args through directly to `vagrant`.  This allows us to retain the vagrant escape hatch, without polluting `vagrant-spk`'s interface.  If alternate, non-vagrant backends for vagrant-spk are developed (say, a native LXC backend for Linux hosts), they may behave differently.

The existing shorthand commands (`up`, `halt`, `destroy`, `global-status`, and `ssh`) will be deprecated.  They will continue to work as they do at present for a while, but will warn users about the new expected expression, and may be removed in future releases of `vagrant-spk` (an approximate proposed date for this removal was 2016-08-01).

**Comment by ocdtrekkie** [comment]
This is already the case, so I'm closing this. (And I know `vagrant-spk vm box update` even works!)
