### ISSUE TITLE
Rename "launcher" to "start-grain"

### ISSUE THREAD

**Issue by paulproteus** [sandstorm-io/vagrant-spk#15]
I want to rename the "launcher" script into something called "start-grain", or at least with "grain" in the title.

Rationale:
- I'd like to minimize the number of unique things Sandstorm app packagers have to know, and they're going to have to know the term grain, so we might as well present them with it.
- No end user will see this, so it's not as if we are going down the path of showing this term to users of the apps themselves.

This is not necessarily a show-stopper for anything, but it strikes me as a thing to do sooner rather than later.

I'm curious for @JamborJan 's and/or @zarvox 's +1 or -1 etc.

**Comment by JamborJan** [comment]
I have no strong opinion here. "start-grain" is a more clear name, the readme of the repo anyway describes the purpose of the "launcher" script well enough. So there are unimportant points on both sides :-)

I have nothing against the change.

**Comment by zarvox** [comment]
+1 on the rename.  If we plan to do it, sooner is better than later.

A single caveat: a direct rename might break behavior against existing repos with `launcher.sh` in them, but I suspect that there's approximately one of those in current usage (paperwork) and you can probably convince @JamborJan to git mv it to the new name. :)

If you make that change, please also update the README and docs appropriately.  (You're probably requesting this change as a result of writing better docs, so this will probably happen automagically.)

**Comment by ocdtrekkie** [comment]
In 2021, I am inclined to just not do this, as there are a lot of apps and documents and eyeballs used to the existing naming scheme. If someone strongly feels still inclined on this, I will reopen it.
