### ISSUE TITLE
vagrant-spk needs to point to newer meteor-spk bundle to support Meteor 1.3

### ISSUE THREAD

**Issue by frigginglorious** [sandstorm-io/vagrant-spk#152]
Project is Meteor 1.3.1

After making with vagrant-spk dev:

When attempting to load a grain, nothing comes up but a loady spinny gif.

Going directly to the iframe URL results in a pending request to load it, which comes back as a failed after 2 minutes, then attempts to load again, then about after 5 minutes returns a 504.

The project was not building in vagrant-spk initially because a node package, fibers, said it needed to be built. I was able to run after installing g++ manually on box.

I still get these warnings, though:
npm WARN package.json meteor-dev-bundle@0.0.0 No description
npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
npm WARN package.json meteor-dev-bundle@0.0.0 No README data

After it builds and runs, I logged in with vagrant-spk ssh to test some things. Don't know if this will help.

vagrant@localhost:/var$ curl http://f98c7611a5f51619e252dd432a8a42d1.local.sandstorm.io:6080/_sandstorm-init?sessionid=07278101882155671c1e4f055235db4bac146cdb91d37a73a23a32158d1e62aa&path=/
[1] 24739

vagrant@localhost:/var$ curl http://f98c7611a5f51619e252dd432a8a42d1.local.sandstorm.io:6080/
Error: Unauthorized [403]
    at Proxy.makeContext (server/proxy.js:1512:15)
    at server/proxy.js:1711:20
    at C (/node_modules/es6-promise.js:12:57)
    at /node_modules/es6-promise.js:17:252
    at t (/node_modules/es6-promise.js:9:473)
    at process._tickCallback (node.js:448:13)[1]+  Done                    curl http://f98c7611a5f51619e252dd432a8a42d1.local.sandstorm.io:6080/_sandstorm-init?sessionid=07278101882155671c1e4f055235db4bac146cdb91d37a73a23a32158d1e62aa

**Comment by paulproteus** [comment]
Hi! What a mess. Any chance you can share your code-in-progress with the whole `.sandstorm/` directory so I can attempt to reproduce this, and track it down?

**Comment by paulproteus** [comment]
BTW, looks like your copy-paste here doesn't contain the output of the second `curl` (that includes the `_sandstorm-init?sessionid=foo`) line. Can you provide the output of that line too, if possible?

**Comment by dwrensha** [comment]
I suspect the main issue here is that we need to upgrade meteor-spk to support meteor 1.3: https://github.com/sandstorm-io/meteor-spk/issues/15

**Comment by frigginglorious** [comment]
@dwrensha actually i ended up upgrading to 1.3 to see if it fixed the issue. I should be able to downgrade it again to the same effect.

Thank you @paulproteus! It's my first meteor project, so please be gentle :P 

https://github.com/frigginglorious/diceStorm

**Comment by dwrensha** [comment]
I just tried running that app with meteor-spk (without vagrant-spk) and the error I got was: 

```
Meteor requires Node v0.10.41 or later.
```

Using a newly-built version of meteor-spk that supports Meteor 1.3.1, I can successfully launch the app. So think we need to ask @kentonv to push a new meteor-spk binary release that supports the new Meteor release.

I did run into some weird issues with the `fibers` module. Doing `nvm set 0.10` fixed it, but meteor-spk should be using its own version of node. I'm currently investigating what's going on here...

**Comment by dwrensha** [comment]
I found the answer to my fibers troubles: https://github.com/sandstorm-io/meteor-spk/pull/16

**Comment by frigginglorious** [comment]
Thanks for looking into it man, appreciate it. Will I be able to successfully run the project in Sandstorm by switching node version and after that PR goes through?

**Comment by paulproteus** [comment]
Hi @frigginglorious !

The easiest way to proceed is to wait for a new version of `meteor-spk` and/or `vagrant-spk`. This is because `meteor-spk` (and `vagrant-spk` by re-using `meteor-spk`) embeds a specific version of node, independent of nvm stuff.

So, short answer: https://github.com/sandstorm-io/meteor-spk/pull/16 by itself won't help, but it's part of what will. I'll ping this issue when there's an update path I recommend for you, in which case `vagrant-spk` by itself should work fine.
