### ISSUE TITLE
Can we please do something about this error message?

### ISSUE THREAD

**Issue by ndarilek** [sandstorm-io/vagrant-spk#158]
There is a certain vagrant-spk failure case that happens sometimes. I'm including the log here in its entirety. I don't know what it says because, for some reason, the error message is split up one character per line. Maybe visually it's a bit odd but you can scan the text in a column, but with a screen reader I have to listen to the entire line, hear the single character, and string them together in my head. I don't have the patience to do that. :) I've seen this error in a few vagrant-spk-generated stacks. This specimen is from the Sandstorm Radicale app at https://github.com/synchrone/sandstorm-radicale. Literally just cloned and ran `vagrant-spk up`.

```
==> default: Running provisioner: shell...
    default: Running: inline script
==> default: stdin: is not a tty
==> default: Downloading Sandstorm version 160...
==> default: c
==> default: u
==> default: r
==> default: l
==> default: :
==> default:  
==> default: (
==> default: 1
==> default: 8
==> default: )
==> default:  
==> default: t
==> default: r
==> default: a
==> default: n
==> default: s
==> default: f
==> default: e
==> default: r
==> default:  
==> default: c
==> default: l
==> default: o
==> default: s
==> default: e
==> default: d
==> default:  
==> default: w
==> default: i
==> default: t
==> default: h
==> default:  
==> default: 2
==> default: 6
==> default: 4
==> default: 0
==> default: 4
==> default: 2
==> default: 7
==> default:  
==> default: b
==> default: y
==> default: t
==> default: e
==> default: s
==> default:  
==> default: r
==> default: e
==> default: m
==> default: a
==> default: i
==> default: n
==> default: i
==> default: n
==> default: g to read
```

Seems to happen when attempting to download Sandstorm? I have no idea what causes it because I just don't have time to piece together the characters, but it's odd how Vagrant seems to mangle the output.

Thanks.

**Comment by paulproteus** [comment]
Yes, definitely. Thanks for filing the bug. For what it's worth, it seems
to say:

curl: (18) connection closed with 2640427 bytes remaining to read.

So it seems like some kind of slow/semi-broken networking issue. We should
probably allow curl more time to do the download. Having said that, I am
curious - if you adjust the Vagrantfile to use NIC type Am79C973 (see
https://github.com/sandstorm-io/vagrant-spk/blob/master/vagrant-spk#L125 )
does that help?

Anyway I can work on fixing the scripts for this. Sadly this is part of
those users' .sandstorm/global-setup.sh but I can submit pull requests once
I have a fix, if you can name me a few vagrant-spk packages that reproduce
the error for you.

**Comment by ndarilek** [comment]
Cool, thanks, I'll give that a shot and report back.

Most of the packages I've encountered doing this are my own, so I can 
fix those files once I know the cause. :) I just hit that today trying 
to fix a11y issues in Radicale and thought I'd file it.

**Comment by dwrensha** [comment]
For what it's worth, I just tried `vagrant-spk vm up` on a bunch of projects, and they all displayed output like the following:

```
==> default: stdin: is not a tty
==> default:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
==> default:                                  Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- 
==> default: --:--:-- --:--:--     0
==> default: 1
==> default: 0
==> default: 0
==> default:  
==> default: 7
==> default: 4
==> default: 9
==> default: 8
==> default: 5
==> default:  
==> default:  
==> default: 1
==> default: 0
==> default: 0
==> default:  
==> default: 7
==> default: 4
==> default: 9
==> default: 8
==> default: 5
==> default:  
==> default:  
==> default:  
==> default:  
==> default: 0
==> default:  
==> default:  
==> default:  
==> default:  
==> default:  
==> default: 0
==> default:  
==> default:  
==> default:  
==> default: 1
==> default: 8
==> default: 6
==> default: k
==> default:  
==> default:  
==> default:  
==> default:  
==> default:  
==> default:  
==> default: 0
==> default:  
==> default: -
==> default: -
==> default: :
==> default: -
==> default: -
==> default: :
==> default: -
==> default: -
==> default:  
==> default: -
==> default: -
==> default: :
==> default: -
==> default: -
==> default: :
==> default: -
==> default: -
==> default:  
==> default: -
==> default: -
==> default: :
==> default: -
==> default: -
==> default: :
==> default: -
==> default: -
==> default:  
==> default:  
==> default: 1
==> default: 8
==> default: 6
==> default: k
```

**Comment by paulproteus** [comment]
Thanks for filing this, @ndarilek . It's now live in the latest version of vagrant-spk; you will need to update, but also, you may need to update any packages that exhibit this behavior.

To do that, you can use this commit:

https://github.com/paulproteus/meteor-todos-sandstorm/commit/adcc22d7ed1821a723eefd39090c9e7e1d778085

as a format-patch:

https://github.com/paulproteus/meteor-todos-sandstorm/commit/adcc22d7ed1821a723eefd39090c9e7e1d778085.patch

apply with command line:

```
curl https://github.com/paulproteus/meteor-todos-sandstorm/commit/adcc22d7ed1821a723eefd39090c9e7e1d778085 | git am
```

to any vagrant-spk package.

**Comment by paulproteus** [comment]
Actually, after trying this against the `sandstorm-radicale` package, I can't seem to convince git to apply this change. So you'll have to apply the changes manually.
