### ISSUE TITLE
vagrant up get's stuck with Windows 10 and VirtualBox 5.0.20 r106931

### ISSUE THREAD

**Issue by pgrm** [sandstorm-io/vagrant-spk#179]
Given the project https://github.com/pgrm/swagger-editor-sandstorm - when I run the `vagrant-spk vm up` nothing happened. When I went into `.sandstorm` directory and ran `vagrant up --debug` I saw that the process get's stuck at the following last 4 lines:

     INFO loader: Loading configuration in order: [:home, :root]
    DEBUG loader: Loading from: root (evaluating)
    DEBUG provisioner: Provisioner defined:
    DEBUG provisioner: Provisioner defined:

after the last line, nothing happens for a couple minutes until I kill vagrant. I tried running other vagrant files, they all worked fine. It also seems to work on my macbook.

Any ideas? I couldn't find anything fruitful online.

**Comment by paulproteus** [comment]
Hi! Unfortunately in my testing, bringing up the VM works fine on my Debian
laptop. with:

$ vagrant --version
Vagrant 1.6.5

Does VirtualBox think the VM is up? Can you force it to shut down, and then
try to bring it up freshly?

**Comment by pgrm** [comment]
I tried removing the VM from VirtualBox by deleting it and all the files and it didn't help. I believe you that it works in Debian - it also works on my OS X maybe someone else is in the unfortunate situation of working on a windows machine and could confirm or disprove this behavior?

**Comment by paulproteus** [comment]
Wow, huh.

(a) maybe I should upgrade Vagrant to a similar version on Debian, for maximal bug reproduction value

(b) Maybe @ocdtrekkie is willing to test this? What do you think, Jake?

Hopefully steps to reproduce are:

```
git clone https://github.com/pgrm/swagger-editor-sandstorm
cd swagger-editor-sandstorm
vagrant-spk vm up
```

**Comment by ocdtrekkie** [comment]
My development PC isn't on Windows 10 yet. I've had upgrading issues.

**Comment by paulproteus** [comment]
@dwrensha tested with vagrant 1.8.3 and ran into this bug in Vagrant: https://github.com/mitchellh/vagrant/issues/7417

If it happens to be easy for @dwrensha to test with 1.8.1 I wonder what other issues you will run into...

**Comment by dwrensha** [comment]
I just tried on Windows 10 with vagrant v1.8.4, vagrant-spk v0.165, VirtualBox 5.0.20, and it worked okay..

**Comment by paulproteus** [comment]
@pgrm any chance it works for you if you upgrade to Vagrant 1.8.4?

**Comment by dwrensha** [comment]
note: I needed to go to https://releases.hashicorp.com/vagrant/1.8.4/ to install 1.8.4, because the main vagrant download page still links to 1.8.3

**Comment by pgrm** [comment]
didn't notice new vagrant versions came out - so with vagrant 1.8.4 and the default windows console, I can run `vagrant up` inside the `.sandsotrm` directory and it works again :+1: - **but** :disappointed: ...

obviously (or not?) I can't use vagrant-spk in the windows command line, so I tried ... to execute `vagrant-spk dev`

- my default command line, [babun](http://babun.github.io/) which reported the following error after killing the process after ~1m of seemingly not doing anything:

````
Calling 'vagrant' 'ssh' '-c' '/opt/app/.sandstorm/build.sh && cd /opt/app/.sandstorm && spk dev --pkg-def=/opt/app/.sandstorm/sandstorm-pkgdef.capnp:pkgdef' in /cygdrive/c/Users/peter/Sync/GitHub/swagger-editor-sandstorm/.sandstorm
Traceback (most recent call last):
  File "../vagrant-spk/vagrant-spk", line 1028, in <module>
    main()
  File "../vagrant-spk/vagrant-spk", line 1025, in main
    operation(args)
  File "../vagrant-spk/vagrant-spk", line 680, in dev
    "spk dev --pkg-def=/opt/app/.sandstorm/sandstorm-pkgdef.capnp:pkgdef"
  File "../vagrant-spk/vagrant-spk", line 294, in call_vagrant_command
    return subprocess.check_call(command, cwd=sandstorm_dir)
  File "/usr/lib/python2.7/subprocess.py", line 535, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 1376, in wait
    pid, sts = _eintr_retry_call(os.waitpid, self.pid, 0)
  File "/usr/lib/python2.7/subprocess.py", line 476, in _eintr_retry_call
    return func(*args)
````

- git bash right away quit with `/usr/bin/env: ‘python2.7’: No such file or directory` however, in the same command line I get:

````
$ python --version
Python 2.7.10
````

I've pulled the latest changes from vagrant spk, the last commit I can see locally is:

    commit ad907fd91021b55980a0f459f09956ffb933cde0
    Merge: e98991a 825b2fb
    Author: Drew Fisher <drew.m.fisher@gmail.com>
    Date:   Wed Jun 8 13:32:35 2016 -0700

        Merge pull request #177 from sandstorm-io/add-comments-about-synced-folders

        Add comments about synced_folders

In the meanwhile the VM is running correctly and I can access http://local.sandstorm.io:6080/ - it's just vagrant-spk which somehow stopped working. And yes, it used to work on my windows 10 laptop ~1 month ago when I started with the aforementioned project - any new thoughts?

Thanks

**Comment by dwrensha** [comment]
I should also note: when I tried this I was using PowerShell.

**Comment by zarvox** [comment]
Hmmm, the shebang line:

```bash
#!/usr/bin/env python2.7
```

means that bash is going to look for an executable named `python2.7`, not `python`, which is needed because on many systems, `python` is `python3`.  If you're running `vagrant-spk` out of a git clone, maybe try modifying that first line of `vagrant-spk` to read:

```bash
#!/usr/bin/env python
```

As for the "`vagrant-spk dev` hangs and appears to do nothing" - does manually running the echoed command (starts with 'vagrant' 'ssh' '-c') from the directory named work?

**Comment by paulproteus** [comment]
Hi @pgrm ,

You wrote:

> obviously (or not?) I can't use vagrant-spk in the windows command line, so I tried to execute vagrant-spk dev with ...

You _should_ be able to use vagrant-spk in the Windows command line. I go through some pains in the installer to add it to %PATH%. I see in your output here that you are managing to use `vagrant-spk`, because this line seems to come from it:

> Calling 'vagrant' 'ssh' '-c' '/opt/app/.sandstorm/build.sh && cd /opt/app/.sandstorm && spk dev --pkg-def=/opt/app/.sandstorm/sandstorm-pkgdef.capnp:pkgdef' in /cygdrive/c/Users/peter/Sync/GitHub/swagger-editor-sandstorm/.sandstorm

But I also see that you're using cygwin. If you use cmd.exe instead of Cygwin, does that help? (Or PowerShell, as @dwrensha suggests.)

Note that in https://docs.sandstorm.io/en/latest/vagrant-spk/installation/ we suggest that Windows users download and install the vagrant-spk via an EXE, rather than via git; however, I see that you are talking about the vagrant-spk git log, which suggests to me that you're getting vagrant-spk via git. Consider getting it via the installer EXE and using PowerShell.

Given that babun uses Cygwin, it will not necessarily do the right thing in the face of our %PATH% modification. But it should be possible to bridge that gap.

**Comment by pgrm** [comment]
@zarvox yes, I can run the commands directly on the VM via VirtualBox that works

@paulproteus - maybe when I read the docs about vagrant-spk I didn't get far enough to actually realize that you can really install it on windows. I'll try that and come back to you with the results, thx

**Comment by paulproteus** [comment]
Great, @pgrm !

**Comment by pgrm** [comment]
@paulproteus ok, so powershell with openssh and vagrant-spk for windows installed works now, thx for the help :+1:

**Comment by paulproteus** [comment]
Great!

**Comment by sharpedavid** [comment]
For what it's worth, I encountered a similar issue when using Babun on Windows. `cmd.exe` worked fine though.

You might consider adding a note to https://docs.sandstorm.io/en/latest/vagrant-spk/packaging-tutorial/. I think the sort of Windows user likely to be interested in Sandstorm is also likely to be using Babun or Cygwin.
