### ISSUE TITLE
Crashes on import of argparse on Python 2.5

### ISSUE THREAD

**Issue by paulproteus** [sandstorm-io/vagrant-spk#18]
https://www.evernote.com/shard/s59/sh/09003436-2e8b-4224-ab09-d6bea7b80024/a006b9a017e7c0aa/deep/0/

argparse wasn't a thing yet in Python 2.5, so Python 2.5 users don't have it.

I think a design goal of `vagrant-spk` is that it should work on all sorts of people's random computers, so it's wise to remove the argparse dependency (perhaps relying on optparse instead, or perhaps inlining it somehow).

@zarvox curious for your +1 -1 on this. I'm going to write this patch as if you've +1'd it but will be eager to hear what you think.

**Comment by zarvox** [comment]
Ahhh.  Yeah, we should probably try to make this work on python2.5, if devs are still stuck using it.  +1 on whatever approach you go with.

**Comment by paulproteus** [comment]
Here's the results of my research:

* `optparse` has no way to implement commands that don't start with `--` as far as I can tell.
* Therefore, we can't show help output that is as useful as we would desire, with the `commands` 
* On @jadeqwang 's machine, there is a python2.7 binary, so we'll use that for now. But `/usr/bin/env python` does point to 2.5.

**Comment by paulproteus** [comment]
Today I plan to not-worry-about-this but tomorrow or later I might try worrying about it again.

**Comment by paulproteus** [comment]
Per the research that @zarvox and I did <https://oasis.sandstorm.io/grain/P7LEvDNJwY7pyAk6DZ9eMs>, it seems safe to make the script be `#!/usr/bin/python2.7`.

So we'll go with that for now, and I'll close this issue.
