### ISSUE TITLE
People might not remember why their :6080 is bound

### ISSUE THREAD

**Issue by paulproteus** [sandstorm-io/vagrant-spk#19]
In https://www.evernote.com/shard/s59/sh/85fb8ee1-acf2-434f-b737-34dc39304749/25eea35f0ecefb6c/deep/0/ , @jadeqwang ran into a problem where she had another Vagrant listening on port 6080. In her case, it was the Vagrant from a Sandstorm checkout.

I would love to see `vagrant-spk` figure out how to resolve this problem, though we might decide it's out of scope. Some things we can do:
- Ask Vagrant/VirtualBox what VMs are running; if some have Sandstorm in the name, we could provide the user a hint that that's where the conflict is.
- It could check if /opt/sandstorm exists and if so, indicate that you might need to `sudo sandstorm stop`.
- `vagrant-spk` could pick a random port number; to do this properly, it would need to also modify the sandstorm.conf within the VM. This is tricky but arguably the best answer.

Curious for people's thoughts.

**Comment by paulproteus** [comment]
Related issue:

`vagrant-spk pack` should arguably take the VM down, since at this point you're unlikely to need it anymore, and it decreases conflicts between the packaging of various apps.

**Comment by ocdtrekkie** [comment]
Closing this one. Now that vagrant-spk uses it's own port independent of Sandstorm, there's only one reason the port should be in use. We have a lot of documentation about halting vagrant-spk vms in the docs and using vagrant global-status to determine what VMs are running, which I think is satisfactory.
