### ISSUE TITLE
Decide how the new "privileged" sandbox should affect vagrant-spk

### ISSUE THREAD

**Issue by paulproteus** [sandstorm-io/vagrant-spk#194]
Context:

- Now that the code for https://github.com/sandstorm-io/sandstorm/pull/2644 has landed, we need to decide how it affects vagrant-spk.

- Let's take notes either here on the issue, or somewhere else but put a link to the notes here on the issue.

- Then with all the facts in front of us, let's figure out what we should actually do.

**Comment by paulproteus** [comment]
Remarks:

- `vagrant-spk` should prefer the userns sandbox so that, one day, we can randomize the user ID that the app runs as, to help identify app bugs.

- `install.sh` can be modified to, in the `-d` case, prefer userns if it can make it available.

- it can check if the sysctl exists by looking in `/proc/sys` (and presumably only modifying the sysctl if `/proc/sys` is read-write)

That seems pretty doable.

**Comment by zarvox** [comment]
The above suggests that no change is needed in `vagrant-spk` to achieve our desired outcome, and that we can close this issue.  @paulproteus do you agree?

**Comment by paulproteus** [comment]
Agreed.
