### ISSUE TITLE
Cut a new release

### ISSUE THREAD

**Issue by zombiezen** [sandstorm-io/vagrant-spk#208]
I'd like to be able to use the new Go stack on a Windows host. :)

**Comment by kentonv** [comment]
@zarvox and @paulproteus used to maintain vagrant-spk. I actually don't really know how it works. I wonder if someone else would like to take over maintainership?

**Comment by ocdtrekkie** [comment]
FWIW, it looks like the /windows-support folder has "Inno Setup Script Wizard" files. http://www.jrsoftware.org/isinfo.php

**Comment by ocdtrekkie** [comment]
@kenton Once we get #211 resolved, if it's possible, getting a release pushed would be really nice, and prevent questions like #212. It looks like release.sh handles everything from versioning to building the Windows EXE (using Inno and Wine) and tagging and uploading the release.
