### ISSUE TITLE
Vagrant box not found 

### ISSUE THREAD

**Issue by peterlee0127** [sandstorm-io/vagrant-spk#212]
Vagrant box can't access.

https://vagrantcloud.com/sandstorm/boxes/debian-jessie64/versions/8.2.1/providers/virtualbox.box

<img width="1146" alt="screen shot 2018-03-05 at 10 24 13 am" src="https://user-images.githubusercontent.com/906325/36955078-1c48dd2a-2061-11e8-9f4c-a17954b478e6.png">

**Comment by ocdtrekkie** [comment]
The release version no longer works, but the git master uses a new box and an updated script. See #210

**Comment by peterlee0127** [comment]
Thanks
