### ISSUE TITLE
vagrant-spk fails to install curl because of a stale package index

### ISSUE THREAD

**Issue by QJKX** [sandstorm-io/vagrant-spk#215]
Hi

https://github.com/sandstorm-io/vagrant-spk/blob/08fc4dbdd2847ad59e3fea25fa480247ff6979b0/vagrant-spk#L185

needs to be

`apt-get update`
`apt-get install -y curl`

(I'm following the tutorial)

**Comment by QJKX** [comment]
Sorry I should have included more context.

Those lines of the script get dumped to a file which is run inside the VM - it's the VM that has a stale package cache.

The current debian curl package is a security update from 2018-03-14. The VM image is likely older than that. https://www.debian.org/security/2018/dsa-4136

**Comment by ocdtrekkie** [comment]
Ah, yes, this makes sense to me. (And on a brief check, pretty much all other instances of apt-get install are preceded by an apt-get update.) I am pretty sure apt-get update runs without asking any queries, do you want to just open a PR to add it or should I?

As a general query this brings up: Do we have the vagrant-spk box update it's own preinstalled packages ever, and if not, shouldn't we?
