### ISSUE TITLE
PHP sample app/tutorial does not work

### ISSUE THREAD

**Issue by ocdtrekkie** [sandstorm-io/vagrant-spk#220]
Everything with the tutorial and PHP sample app works out great... except the app doesn't start. I'm guessing between moving to Stretch and PHP 7, things broke. Below is the debug log I'm working from.

https://docs.sandstorm.io/en/latest/vagrant-spk/packaging-tutorial/
https://github.com/sandstorm-io/php-app-to-package-for-sandstorm

Perhaps @Rivierg might have some input here?

> Debug log: Untitled Example App instance
...** SANDSTORM SUPERVISOR: Starting up grain. Sandbox type: userns
chown: invalid user: 'mysql'
Cannot change ownership of the database directories to the 'mysql'
user.  Check that you have the necessary permissions and try again.
waiting for mysql to be available at /var/run/mysqld/mysqld.sock
2018-04-23  0:45:41 140581096079936 [Note] /usr/sbin/mysqld (mysqld 10.1.26-MariaDB-0+deb9u1) starting as process 30 ...
/usr/sbin/mysqld: One can only use the --user switch if running as root
[23-Apr-2018 00:45:41] ERROR: unable to bind listening socket for address '/run/php/php7.0-fpm.sock': Read-only file system (30)
[23-Apr-2018 00:45:41] ERROR: FPM initialization failed
waiting for mysql to be available at /var/run/mysqld/mysqld.sock
waiting for mysql to be available at /var/run/mysqld/mysqld.sock
waiting for mysql to be available at /var/run/mysqld/mysqld.sock
waiting for mysql to be available at /var/run/mysqld/mysqld.sock
...

**Comment by ocdtrekkie** [comment]
Actually, possibly the best person to ask/code to look at is @JC5's: https://github.com/firefly-iii/firefly-iii which is recent/modern/updated and runs PHP7.1 with MySQL. I've compared his code and the vagrant-spk lemp stack, and in terms of the mysql-specific code, I'm not really a whole lot that's different.

**Comment by ocdtrekkie** [comment]
My closest guess right now is that where @zarvox patched out MySQL's attempt to use a mysql user account has bitrotted (possibly because of Stretch, Firefly's Vagrantfile is still set to Jessie): https://github.com/sandstorm-io/vagrant-spk/blob/master/stacks/lemp/setup.sh#L33

**Comment by ocdtrekkie** [comment]
Also, as I was digging around the commit history/blames, I noticed @JamborJan edited the little sed-party on my.cnf, and he might also be able to help!

**Comment by JamborJan** [comment]
I'll take a look at this as soon as possible. I have switched to PHP7 with the wordpress package too, see https://github.com/wpsandstorm/wordpress-sandstorm/commit/1db990e5c6830713a8c008e9502e4f4e165c060d.

Please pay attention: I switched to Debian Buster (testing) due to the fact that I needed some really up to date packages.

**Comment by ocdtrekkie** [comment]
This seems to fix PHP on the LESP stack: https://github.com/sandstorm-io/vagrant-spk/pull/214/commits/e674fcc000c1170844445669a4d0e5e03110a8fe (This fix was shamelessly stolen from @JC5's Firefly III .sandstorm folder.)

The same change should fix the PHP side of the issue on the LEMP stack as well. Which just leaves the MySQL issue to fix.

**Comment by JC5** [comment]
Glad to hear my fix helps! :D

**Comment by ocdtrekkie** [comment]
I bought you a coffee for it. Still have no idea why your MySQL works and mine doesn't. Not only can I not see why your MySQL doesn't try to use the `mysql` user, it looks like you use a `firefly` user on MySQL instead and I have no idea where that comes from. o_o

**Comment by JC5** [comment]
This line disables the mysql user in the MySQL config:

https://github.com/firefly-iii/firefly-iii/blob/master/.sandstorm/setup.sh#L78

I must admit I haven't checked which user it is being replaced by but that is the related config var.

**Comment by ocdtrekkie** [comment]
Yeah, the same line exists in vagrant-spk, which is why it's weird that I'm getting the error above, and you aren't. o_o

**Comment by ocdtrekkie** [comment]
Okay, based on the link above, I went ahead and patched in the apt source for MySQL proper, added in the PHP 7 fixes from my LESP stack PR, and both services appear to start and the sample index page loads. However, there's a permission error with mysql I need to tackle yet.

I'm going to bed, but I'm 95% there now.
