### ISSUE TITLE
To Do: Update Go stack

### ISSUE THREAD

**Issue by ocdtrekkie** [sandstorm-io/vagrant-spk#232]
Now we're probably close enough to "everything works" to start reporting things that don't (or probably don't) as an issue. I was looking at https://github.com/sandstorm-io/vagrant-spk/blob/master/stacks/golang/setup.sh and realizing that it adds jessie-backports to install golang, and since we're on Stretch now, we should probably fix that.

@zenhack Do you have any opinions on the version of golang included with Stretch? It appears to default to golang-1.7 but it looks like golang-1.8 is available. https://packages.debian.org/stretch/devel/golang https://packages.debian.org/stretch/devel/golang-1.8

Stretch backports will get us golang-1.10: https://packages.debian.org/stretch-backports/devel/golang

**Comment by zenhack** [comment]
Quoting Jacob Weisz (2018-05-28 13:12:49)

>    Stretch backports will get us golang-1.10:
>    [5]https://packages.debian.org/stretch-backports/devel/golang

Let's do 1.10.

**Comment by ocdtrekkie** [comment]
Would "just" replacing jessie with stretch everywhere in setup.sh then, to use stretch backports, work? We don't have a Go test app lying around.

**Comment by zenhack** [comment]
It should. I can also try to find time to test.
