### ISSUE TITLE
404 Not Found when vagrant vm up in initializing progess

### ISSUE THREAD

**Issue by urakagi** [sandstorm-io/vagrant-spk#238]
I'm using Windows vagrant-spk (I think's it's v0.230, but I can't find a way to check version), and when I do `vagrant-spk vm up` first time, I get this error:

```
    default: Reading state information...
    default: The following additional packages will be installed:
    default:   libcurl3
    default: The following NEW packages will be installed:
    default:   curl libcurl3
    default: 0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
    default: Need to get 518 kB of archives.
    default: After this operation, 989 kB of additional disk space will be used.
    default: Err:1 http://deb.debian.org/debian stretch/main amd64 libcurl3 amd64 7.52.1-5+deb9u3
    default:   404  Not Found [IP: 151.101.76.204 80]
    default: Ign:2 http://deb.debian.org/debian stretch/main amd64 curl amd64 7.52.1-5+deb9u3
    default: Err:1 http://security.debian.org/debian-security stretch/updates/main amd64 libcurl3 amd64 7.52.1-5+deb9u3
    default:   404  Not Found [IP: 151.101.76.204 80]
    default: Err:2 http://security.debian.org/debian-security stretch/updates/main amd64 curl amd64 7.52.1-5+deb9u3
    default:   404  Not Found [IP: 151.101.76.204 80]
    default: E: Failed to fetch http://security.debian.org/debian-security/pool/updates/main/c/curl/libcurl3_7.52.1-5+deb9u3_amd64.deb  404  Not Found [IP: 151.101.76.204 80]
    default: E: Failed to fetch http://security.debian.org/debian-security/pool/updates/main/c/curl/curl_7.52.1-5+deb9u3_amd64.deb  404  Not Found [IP: 151.101.76.204 80]
    default: E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
Command failed with a non-zero exit status (1).
```

And then `vagrant-spk init` will return `spk: command not found`.
It seems like the download URL is wrong, but I can't find the URL in setting files.
How to resolve this problem? Thanks.

**Comment by ocdtrekkie** [comment]
https://github.com/sandstorm-io/vagrant-spk/commit/9cb56c4ca740e362a0d001945f1b126ac2ff49ed which I think is in global-setup.sh in your .sandstorm directory.

Sent from my Windows 10 phone

From: 蔡仲明 (Romulus Urakagi Tsai)
Sent: Thursday, July 5, 2018 4:51 AM
To: sandstorm-io/vagrant-spk
Cc: Subscribed
Subject: [sandstorm-io/vagrant-spk] 404 Not Found when vagrant vm up ininitializing progess (#238)

I'm using Windows vagrant-spk (I think's it's v0.230, but I can't find a way to check version), and when I do vagrant-spk vm up first time, I get this error:
    default: Reading state information...
    default: The following additional packages will be installed:
    default:   libcurl3
    default: The following NEW packages will be installed:
    default:   curl libcurl3
    default: 0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
    default: Need to get 518 kB of archives.
    default: After this operation, 989 kB of additional disk space will be used.
    default: Err:1 http://deb.debian.org/debian stretch/main amd64 libcurl3 amd64 7.52.1-5+deb9u3
    default:   404  Not Found [IP: 151.101.76.204 80]
    default: Ign:2 http://deb.debian.org/debian stretch/main amd64 curl amd64 7.52.1-5+deb9u3
    default: Err:1 http://security.debian.org/debian-security stretch/updates/main amd64 libcurl3 amd64 7.52.1-5+deb9u3
    default:   404  Not Found [IP: 151.101.76.204 80]
    default: Err:2 http://security.debian.org/debian-security stretch/updates/main amd64 curl amd64 7.52.1-5+deb9u3
    default:   404  Not Found [IP: 151.101.76.204 80]
    default: E: Failed to fetch http://security.debian.org/debian-security/pool/updates/main/c/curl/libcurl3_7.52.1-5+deb9u3_amd64.deb  404  Not Found [IP: 151.101.76.204 80]
    default: E: Failed to fetch http://security.debian.org/debian-security/pool/updates/main/c/curl/curl_7.52.1-5+deb9u3_amd64.deb  404  Not Found [IP: 151.101.76.204 80]
    default: E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
Command failed with a non-zero exit status (1).
And then vagrant-spk init will return spk: command not found.
It seems like the download URL is wrong, but I can't find the URL in setting files.
How to resolve this problem? Thanks.

**Comment by ocdtrekkie** [comment]
As a note, I would also replace the files in your .sandstorm directory with whatever copies are in the /stacks folder of the vagrant-spk repo for whatever type of stack you are using. Those are probably broken in your vagrant-spk too.

Building with an out of date Windows build is a bit of a pain, but at the end of the day its just assembling these scripts, so you can update them manually, thankfully.

I'll see if we can get a proper upgraded release on the 8th.

Sent from my Windows 10 phone

From: 蔡仲明 (Romulus Urakagi Tsai)
Sent: Thursday, July 5, 2018 4:51 AM
To: sandstorm-io/vagrant-spk
Cc: Subscribed
Subject: [sandstorm-io/vagrant-spk] 404 Not Found when vagrant vm up ininitializing progess (#238)

I'm using Windows vagrant-spk (I think's it's v0.230, but I can't find a way to check version), and when I do vagrant-spk vm up first time, I get this error:
    default: Reading state information...
    default: The following additional packages will be installed:
    default:   libcurl3
    default: The following NEW packages will be installed:
    default:   curl libcurl3
    default: 0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
    default: Need to get 518 kB of archives.
    default: After this operation, 989 kB of additional disk space will be used.
    default: Err:1 http://deb.debian.org/debian stretch/main amd64 libcurl3 amd64 7.52.1-5+deb9u3
    default:   404  Not Found [IP: 151.101.76.204 80]
    default: Ign:2 http://deb.debian.org/debian stretch/main amd64 curl amd64 7.52.1-5+deb9u3
    default: Err:1 http://security.debian.org/debian-security stretch/updates/main amd64 libcurl3 amd64 7.52.1-5+deb9u3
    default:   404  Not Found [IP: 151.101.76.204 80]
    default: Err:2 http://security.debian.org/debian-security stretch/updates/main amd64 curl amd64 7.52.1-5+deb9u3
    default:   404  Not Found [IP: 151.101.76.204 80]
    default: E: Failed to fetch http://security.debian.org/debian-security/pool/updates/main/c/curl/libcurl3_7.52.1-5+deb9u3_amd64.deb  404  Not Found [IP: 151.101.76.204 80]
    default: E: Failed to fetch http://security.debian.org/debian-security/pool/updates/main/c/curl/curl_7.52.1-5+deb9u3_amd64.deb  404  Not Found [IP: 151.101.76.204 80]
    default: E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
Command failed with a non-zero exit status (1).
And then vagrant-spk init will return spk: command not found.
It seems like the download URL is wrong, but I can't find the URL in setting files.
How to resolve this problem? Thanks.

**Comment by ocdtrekkie** [comment]
@urakagi For an existing app folder, easiest solution to this is, as mentioned above, adding the `apt-get update` into your global-setup.sh, but 0.236 has been released of vagrant-spk which has fixes for all of the issues you've had this past week. :)

**Comment by urakagi** [comment]
Thank you @ocdtrekkie and @kentonv ! I'll close the issue.
