### ISSUE TITLE
Cleanup: Function that recommends sandstorm/jessie64

### ISSUE THREAD

**Issue by ocdtrekkie** [sandstorm-io/vagrant-spk#244]
So this function mostly just checks if a specific version of the jessie box is in use and complains about it. vagrant-spk now defaults to stretch, it's actually the box this function that recommends which no longer exists at all and doesn't work, and we've settled on official contrib boxes working fine.

https://github.com/sandstorm-io/vagrant-spk/blob/master/vagrant-spk#L320

Honestly we can probably mostly get rid of this? If anything maybe we should check for uses of sandstorm/jessie64 and recommend they change it to debian/contrib-jessie64... or stretch64.

**Comment by zenhack** [comment]
Yeah I'd be in favor of just deleting that whole swath of code.

**Comment by ocdtrekkie** [comment]
I might look at doing the thing where we detect if they were trying to use the sandstorm/ box, just because it's been such a prevalent complaint when people try to rebuild apps, and I don't see it not being a question soon. But even that would be shorter/cleaner than this.
