### ISSUE TITLE
Plan to transition to contrib-buster64

### ISSUE THREAD

**Issue by ocdtrekkie** [sandstorm-io/vagrant-spk#250]
We should look to upgrading vagrant-spk's default VM to buster: https://app.vagrantup.com/debian/boxes/contrib-buster64

As part of this, we should attempt to make stacks less dependent on specific versions of Debian, so that the scripts are likely to run successfully even if the user wishes to change out the box used and upgrades for new releases are less painful so that we can encourage the use of the `upgradevm` command intended for inclusion with 1.0.

**Comment by ocdtrekkie** [comment]
If we cannot avoid references to something like stretch-backports or the like, we may want to consider detecting the box version as part of the stack setup script and injecting the correct version.

Examples of where this might come up currently:
https://github.com/sandstorm-io/vagrant-spk/blob/master/stacks/lemp/setup.sh#L10
https://github.com/sandstorm-io/vagrant-spk/blob/master/stacks/golang/setup.sh#L11

**Comment by ocdtrekkie** [comment]
We know that the basics of vagrant-spk at least work fine with Buster, because @cdubz has already done it: https://github.com/babybuddy/babybuddy-sandstorm (Fun side note, `vagrant-spk upgradevm` after the command is merged would actually _downgrade_ this VM.)

**Comment by cdubz** [comment]
For the record, I made this change because [Django 3.x only supports Python 3.6+](https://docs.djangoproject.com/en/3.0/releases/3.0/#python-compatibility) while [stretch has Python 3.5.x](https://packages.debian.org/stretch/python3). Moving to buster seemed more straightforward than trying a backport of some sort. So this issue is important for future Django support (though Django 2.x is fine on Python 3.5).

**Comment by ocdtrekkie** [comment]
I would 100% agree on that being the more straightforward way to go. :) Fundamentally vagrant-spk should mostly work on any jessie and up Debian flavor, as long as the contrib- box with vboxsf support is used. We want to move in the direction of pushing more recent code in Sandstorm packages in the future, so we want to "unstick" a lot of it.

**Comment by ocdtrekkie** [comment]
Fixed by #291
