### ISSUE TITLE
enter-grain doesn't allow visibility into /var

### ISSUE THREAD

**Issue by ocdtrekkie** [sandstorm-io/vagrant-spk#251]
Being unable to view the grain's data volume can cause a lot of issues for troubleshooting app development.

(@abliss also mentioned not being able to use `ps` because of the lack of /proc, but I am not sure if that's a bug, because it's not mounted for Sandstorm apps, so ideally we want it broken in the vagrant-spk dev environment too? It is worth discussing if /proc is indeed broken for apps in vagrant-spk dev, not just enter-grain, and whether or not devs should have a way to access it for troubleshooting.)

**Comment by zenhack** [comment]
Quoting Jacob Weisz (2020-01-28 12:58:02)

>    Being unable to view the grain's data volume can cause a lot of issues
>    for troubleshooting app development.

These are available _relatively_ easily in /opt/sandstorm/var/grains,
maybe we just need to write a simple wrapper that makes it more
ergonomic to drop yourself in there?

>    ([1]@abliss also mentioned not being able to use ps because of the lack
>    of /proc, but I am not sure if that's a bug, because it's not mounted
>    for Sandstorm apps, so ideally we want it broken in the vagrant-spk dev
>    environment too? It is worth discussing if /proc is indeed broken for
>    apps in vagrant-spk dev, not just enter-grain, and whether or not devs
>    should have a way to access it for troubleshooting.)

It's totally fine, expected, and desirable for apps to not have this,
but it would be nice for it to be available for development.

There are some other things, like launching stuff in debuggers, that
would be really nice but are basically impossible right now. I should
open some issues about some things.

The debugger thing probably needs support in Sandstorm itself, since
vagrant-spk as a wrapper can't do much there.

**Comment by zenhack** [comment]
This looks to be bitrot; when entering the grain the enter_grain command sets its uid & gid to 1000/1000 which used to be what sandstorm did for the grains, but afaik it now randomizes them. So instead we should detect the actual uid & gid that the grain is running as.

**Comment by abliss** [comment]
Nice catch. and apparently enter-grain is written in rust for some reason?! Someone will have to learn enough rust to update it.
Perhaps the magical ssh command that vagrant-spk uses to detect the pid of grain in dev mode can be augmented to also print out the uid/gid? Then passed to the enter-grain binary as cmdline args?
Or perhaps we can ditch rust binar in favor of a suitably crafted `nsenter` cmdline?

**Comment by ocdtrekkie** [comment]
I feel like if we announce "someone unnecessarily wrote something in Rust, and now we need help to keep it in Rust", Rust developers will appear from nowhere and fix the issue...

My understanding was nsenter was inadequate at the time for some reason? There are two different branches about it: https://github.com/sandstorm-io/vagrant-spk/tree/nsenter-devgrain and https://github.com/sandstorm-io/vagrant-spk/tree/plus-asheesh-nsenter which might provide insight or a starting point.

**Comment by zenhack** [comment]
I know enough rust to maintain this. I'll figure it out.

There's some misc. bitrot that should be fixed too; it doesn't build on recent toolchains (I've fixed that locally already) and could use a bit of cleanup generally.

I'm ok with having Rust in our stack in various places. The collections grain is also written in Rust.

Honestly, I'd sleep better if we had less C++, but it obviously doesn't make sense to start re-writing things.

**Comment by paulproteus** [comment]
I wrote it in Rust because I couldn't rely on `nsenter` to be recent
enough. Nowadays I think you can rely on that, thankfully. :) (Plus, I
thought learning some Rust would be fun, and it was.)

**Comment by ocdtrekkie** [comment]
@paulproteus So does one of those branches probably mostly work then?

**Comment by zenhack** [comment]
branches? is there an implementation using nsenter somewhere?

**Comment by ocdtrekkie** [comment]
I linked them above. "devjoin" is the command name that preceded "enter-grain".

**Comment by paulproteus** [comment]
@ocdtrekkie I suspect that https://github.com/sandstorm-io/vagrant-spk/commit/d2c8a7095498962d65825f3cca59e5b3ed80153e#diff-ea16ba16bb55540b301bc1309c887b74L654 mostly works on current `nsenter`. That, or the `strace -ff` version below it.

**Comment by zenhack** [comment]
How much of this code is shared with the current implementation? It'd be nice to drop the dependency, but I don't know if I think it's worth the trouble, at least right now, if it means picking up a bunch of untested gluing together of shell commands *and* still having the same bug to fix.

It's a little ugly to have the rust binary in there, but imo there's a low threshold before it becomes not worth the trouble.

Maybe I can just push a fix for the current issue (easy), and we can think about stripping out the custom binary separately?

**Comment by ocdtrekkie** [comment]
I think most of the code in the branch to add the feature is the scaffolding like listing grains you can enter. It's plausible/possible we can test this by using `vagrant-spk vm ssh` and then running the nsenter command we believe might work? You can run an existing `enter-grain` to see what child PID you'd need for the active grain, then manually enter that into the test `nsenter` command.

That being said, I am the sort of person who says "merge what's better than what we have". And a fixed binary is better than the one we have now.

**Comment by zenhack** [comment]
> That being said, I am the sort of person who says "merge what's better than what we have". And a fixed binary is better than the one we have now.

OK, I'm going to go ahead and do that, and we can maybe talk about whether it's worth replacing later.
