### ISSUE TITLE
vagrant-spk dev fails with Meteor under Windows

### ISSUE THREAD

**Issue by ndarilek** [sandstorm-io/vagrant-spk#26]
bash-3.1$ vagrant-spk dev
Calling 'vagrant' 'ssh' '-c' '/opt/app/.sandstorm/build.sh && cd /opt/app/.sands
torm && spk dev --pkg-def=/opt/app/.sandstorm/sandstorm-pkgdef.capnp:pkgdef' in
c:\users\nolan\Projects\Scheduler\.sandstorm

WARNING: The output directory is under your source tree.

npm WARN package.json meteor-dev-bundle@0.0.0 No description
npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
npm WARN package.json meteor-dev-bundle@0.0.0 No README data

> fibers@1.0.5 install /opt/app/.sandstorm/bundle/programs/server/node_modules/f
ibers
> node ./build.js

`linux-x64-v8-3.14` exists; testing
Binary is fine; exiting
npm ERR! Error: UNKNOWN, symlink '../semver/bin/semver'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.16.0-4-amd64
npm ERR! command "/home/vagrant/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.l
inux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node" "/ho
me/vagrant/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.brows
er+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm" "install"
npm ERR! cwd /opt/app/.sandstorm/bundle/programs/server
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.4.28
npm ERR! path ../semver/bin/semver
npm ERR! code UNKNOWN
npm ERR! errno -1
npm ERR! not ok code 0
App is now available from Sandstorm server. Ctrl+C to disconnect.
WriteResult({ "nInserted" : 1 })

I don't see a semver directory anywhere in .sandstorm/bundle.

I used to run Meteor on Windows under Vagrant, and remember having to do a bunch of trickery to work around my app running in a shared directory. I wonder if it might be better/easier for the app to build its bundle on a guest filesystem, one that won't fail because of path length limits or casing issues.

**Comment by zarvox** [comment]
Fixed in e859521f6a6888ecb521e67a266d9bd178511f01 by using your suggestion of building the bundle in the guest directory. :)

**Comment by paulproteus** [comment]
< 3
