### ISSUE TITLE
Question: Advice on a node app using Yarn?

### ISSUE THREAD

**Issue by spyjoshx** [sandstorm-io/vagrant-spk#267]
This is my first time trying to package a Sandstorm app, so if my questions are very noob-ish, please excuse me.

I'm trying to package a node app, specifically Riot.IM, and am running into dependency issues with Yarn when running `vagrant-spk dev`. I was wondering if anyone has experience with Yarn, and could help me figure out how to install it into the VM.

**Comment by ocdtrekkie** [comment]
Do you have a repo and/or an error message we can look at?

The other question, specifically regarding Riot.IM, is how you plan to handle the network access? I think we've discussed Matrix in Sandstorm (@zenhack?) before and there are some significant challenges you'll probably have to overcome.

**Comment by zenhack** [comment]
IIRC @abliss experimented with porting a matrix server; maybe he can offer some advice and/or point to WIP?

And yes, more detail/specific error messages would make it easier for us to help.

How tightly coupled is riot to the backend server? is your plan to do a full matrix server + riot frontend, or to point riot at a separate server? (I'm a little fuzzy on how all the pieces fit together, so forgive me if the question doesn't make a lot of sense).

**Comment by abliss** [comment]
IIUC Riot itself is a "nobackend" app, i.e. it is only necessary to serve its static content. So you can do all the yarn stuff at build time and just ship a grain that copies the static assets to the usual place, and serve it through the  public id.

**Comment by spyjoshx** [comment]
@abliss Thanks! That helps a lot. I was thinking of doing that, but was going to try to do it the "proper" way. I did think that would probably be a lot easier. Thanks!

**Comment by abliss** [comment]
@spyjoshx I would love to collaborate on getting riot/matrix working on sandstorm. I've messed with it a bit, but don't yet have much worth sharing. You can hit me up here, or on IRC or matrix.org. I'd love to schedule some synchronous cohacking on it if you're interesting.
