### ISSUE TITLE
Key not found in keyring when trying to package a forked app.

### ISSUE THREAD

**Issue by ankitmhn** [sandstorm-io/vagrant-spk#271]
I'm trying to package my fork of [Rocket.Chat](https://rocket.chat/) using `vagrant-spk pack` but I get an stating `vfnwptfn02ty21w715snyyczw0nqxkv3jvawcah10c6z7hj1hnu0: key not found in keyring`. 
I think I understand why I get this error but how do I circumvent this? 
[sandstorm-pkgdef .capnp.txt](https://github.com/sandstorm-io/vagrant-spk/files/4765642/sandstorm-pkgdef.capnp.txt)

**Comment by ocdtrekkie** [comment]
So, the original app author has the private key in their keyring for that app ID. You need to generate your own to package the app. The publishing guide has details about generating a new app key: https://docs.sandstorm.io/en/latest/developing/publishing-apps/

Note that you cannot upgrade a grain from one app ID to another easily. And if you're looking to publish to the market, we probably need to talk about the app replacement process. (Let us know if this is where you are looking to go!)

**Comment by ankitmhn** [comment]
Thank you for your response.

Since RocketChat has discontinued its support for Sandstorm, I'm having to use an older commit in from their repo to modify and then repackage the app. I don't intend to publish this app to the Sandstorm app store but I'm just hacking it for my own internal use. I don't even need to migrate grains to a new app ID but only generate spk file.

**Comment by ocdtrekkie** [comment]
Okay, then using the `keygen` command as described in the link and putting that key in your pkgdef file will be all you need to worry about. :)
