### ISSUE TITLE
Error on running vagrant-spk vm up on a new machine.

### ISSUE THREAD

**Issue by ankitmhn** [sandstorm-io/vagrant-spk#273]
I am trying to setup a new dev machine for developing Sandstorm and Sandstorm apps. On this new mahcine, I follwed the instructions [here](https://docs.sandstorm.io/en/latest/vagrant-spk/installation/) to install the vagrant-spk.

Now I when I run `vagrant-spk vm up` in an app repo (even the sample PHP app), I get the following error: 
```
The box you're attempting to add doesn't support the provider (Vagrant::Errors::BoxAddNoMatchingProvider)
you requested. Please find an alternate box or use an alternate
provider. Double-check your requested provider to verify you didn't
simply misspell it.

If you're adding a box from HashiCorp's Vagrant Cloud, make sure the box is
released.

Name: debian/contrib-stretch64
Address: https://vagrantcloud.com/debian/contrib-stretch64
Requested provider: [:libvirt]
The box you're attempting to add doesn't support the provider
you requested. Please find an alternate box or use an alternate
provider. Double-check your requested provider to verify you didn't
simply misspell it.

If you're adding a box from HashiCorp's Vagrant Cloud, make sure the box is
released.

Name: debian/contrib-stretch64
Address: https://vagrantcloud.com/debian/contrib-stretch64
Requested provider: [:libvirt]
Command failed with a non-zero exit status (1).
```

I think I may have installed an incorrect dependancy somewhere but I'm not sure which. What should I do? Thanks!

**Comment by ocdtrekkie** [comment]
Generally speaking, if Vagrant works, vagrant-spk should work. How did you install Vagrant, and what platform/distro are you running it on?

**Comment by ankitmhn** [comment]
This new machine is an Ubuntu 18.04. I had installed `vagrant` using the `apt-get install vagrant` method, IIRC.

**Comment by ankitmhn** [comment]
This is on a Ubuntu 18.04 machine. Here's the output from the tools:

1. `vagrant version`: ```Installed Version: 2.0.2

Vagrant was unable to check for the latest version of Vagrant.
Please check manually at https://www.vagrantup.com
```
2. `vagrant-spk --version` : `vagrant-spk v1.0`
3. `VirtualBox --help` : ```Oracle VM VirtualBox VM Selector v6.1.10
(C) 2005-2020 Oracle Corporation
All rights reserved.```

**Comment by ocdtrekkie** [comment]
Ah, you have a very old version of Vagrant (January 2018) with a much newer version of Virtualbox. I would look at Vagrant's website for instructions on installing the latest Vagrant and you should be all good to go.

**Comment by ocdtrekkie** [comment]
I see your edit now, great! I'll close this.
