### ISSUE TITLE
Proposal: Create a "master always works" policy for vagrant-spk

### ISSUE THREAD

**Issue by paulproteus** [sandstorm-io/vagrant-spk#28]
I propose that we set a policy for `vagrant-spk` that master always works.

Given that, there is a question about what "works" means. I think it means:

If you work through https://docs.sandstorm.io/en/latest/vagrant-spk/packaging-tutorial/ using current `master` of `vagrant-spk`, you should always be able to get to the end of the tutorial successfully, or if not, then `vagrant-spk` should print useful error messages telling you what to do, or it should print a useful error message saying that it can't work at _all_ due to some detail about your system.
- I think one logical conclusion of the above is that if VirtualBox is missing, we should tell the user to install VirtualBox, and move the libvirt driver to some kind of "experimental" status, requiring an "experimental" flag passed in to `vagrant-spk` as a command line argument, since it doesn't work as readily out-of-the-box nor as consistently across operating systems (even Debian vs. Fedora) as the VirtualBox backend. It's OK with me if we do _also_ tell people they can try libvirt, so long as we make it clear that it's experimental; unless it's equally well-maintained as the VirtualBox backend, I'd like to require people explicitly request the use of it.
- It would also be nice to spend some time cleaning up the output in the case of common error messages. One example is that in the case of e.g. port 6080 being already used, we should make sure useful messages.

I'm OK with owning those tasks. I want to make sure there's consensus for this before I prioritize it.

I think reliability is more important than flexibility in the case of `vagrant-spk` since it's going to be many Sandstorm app developers' first exposure to packaging, as well as a daily-use tool for Sandstorm package maintainers. My personal concern about this comes from spending a while of my time today running into libvirt-related problems today, and deciding I want to make the package I was trying to make more than I want to make sure vagrant-spk fully supports libvirt (so I took some time to install VirtualBox properly and was back on track).

A different but related thing is that we could commit to a release cycle for `vagrant-spk`, and then advise people to use releases rather than master. Having version tags is probably a good idea anyway, so that I can say "These docs were written against `vagrant-spk` 0.93" or something on the docs pages, though I'd like both (a) have releases and (b) keep master constantly usable.

Sorry if this comes off as negative about our libvirt support. I do think it's useful.

**Comment by ocdtrekkie** [comment]
I am going to close this one, because we do only merge working changes into the master branch, I believe we do officially instruct and require Virtualbox as the backend, and the 6080 issue is mostly resolved by vagrant-spk using 6090 now. Also, am able to push more frequent releases now too.
