### ISSUE TITLE
Add .gitignore so that Vagrant generated files are not versioned

### ISSUE THREAD

**Issue by paulproteus** [sandstorm-io/vagrant-spk#30]
**What I did**

`git add .sandstorm`

**What I expected to happen**

My Sandstorm packaging files are added to git, and no system-specific state (like Vagrant state) is added to git.

**What happened instead**

Vagrant state was added to git.

**Proposal**

`vagrant-spk` should create a `.sandstorm/.gitignore` file with the contents of:

```
.vagrant
```

and place it in `.sandstorm/.gitignore`. Since it lives in `.sandstorm/` rather than the top level directory, it will add to (rather than replace) any existing `.gitignore` rules.

**Details**

For the fun of it, here is a terminal transcript in which I was surprised.

```
➜  0bin git:(master) ✗ vagrant-spk init
Calling 'vagrant' 'ssh' '-c' 'spk init -p 8000 --keyring=/host-dot-sandstorm/sandstorm-keyring --output=/opt/app/.sandstorm/sandstorm-pkgdef.capnp  -- /opt/app/.sandstorm/launcher.sh' in /home/paulproteus/projects/0bin-package/0bin/.sandstorm
** WARNING: Keys are being added to:
**   /host-dot-sandstorm/sandstorm-keyring
** Please make a backup of this file and keep it safe. If you lose your keys,
** you won't be able to update your app. If someone steals your keys, they
** will be able to post updates for your app. (Use -q to quiet this warning.)
wrote: /opt/app/.sandstorm/sandstorm-pkgdef.capnp
Connection to 127.0.0.1 closed.
➜  0bin git:(master) ✗ ls
compress.sh  docs  libs  README.rst  screenshot.png  setup.py  tools  zerobin  zerobin.py
➜  0bin git:(master) ✗ nano -w .sandstorm/sandstorm-pkgdef.capnp 
➜  0bin git:(master) ✗ git add .sandstorm/
➜  0bin git:(master) ✗ ls .sandstorm 
build.sh  global-setup.sh  launcher.sh  sandstorm-pkgdef.capnp  setup.sh  stack  Vagrantfile
➜  0bin git:(master) ✗ git add .sandstorm/
➜  0bin git:(master) ✗ git commit -m 'Initial packaging'
[master d64401d] Initial packaging
 13 files changed, 316 insertions(+)
 create mode 100644 .sandstorm/.vagrant/machines/default/virtualbox/action_provision
 create mode 100644 .sandstorm/.vagrant/machines/default/virtualbox/action_set_name
 create mode 100644 .sandstorm/.vagrant/machines/default/virtualbox/id
 create mode 100644 .sandstorm/.vagrant/machines/default/virtualbox/index_uuid
 create mode 100644 .sandstorm/.vagrant/machines/default/virtualbox/private_key
 create mode 100644 .sandstorm/.vagrant/machines/default/virtualbox/synced_folders
 create mode 100644 .sandstorm/Vagrantfile
 create mode 100755 .sandstorm/build.sh
 create mode 100644 .sandstorm/global-setup.sh
 create mode 100755 .sandstorm/launcher.sh
 create mode 100644 .sandstorm/sandstorm-pkgdef.capnp
 create mode 100644 .sandstorm/setup.sh
 create mode 100644 .sandstorm/stack
```

**Comment by paulproteus** [comment]
Unless @zarvox or others gives this a -1, I will aim to implement this sometime soon.

**Comment by zarvox** [comment]
+1.

I guess this requires:

1. Detect if this repo is tracked with git (walk up folders until you see a `.git` folder)
2. If so, create .gitignore file with `.vagrant`
3. `git add .sandstorm/.gitignore` ?  Not sure if this should happen by default, but probably?
4. If we're git adding .gitignore, should we git add the rest of the files?  Maybe we should do that too.

**Comment by paulproteus** [comment]
FWIW if the user does `git add .sandstorm` it'll cause the `git add .sandstorm/gitignore` so I suggest we skip step 3.

Since the file has effect if and only if the thing is a git repo, I'd err on the side of less magic and always generate the file.

**Comment by paulproteus** [comment]
@zarvox I aim to implement your plan, but skip the "detect" step, and skip the "git add" step. Is that OK by you? Pull request forthcoming.

(cc: @phildini who just ran into this issue)
