### ISSUE TITLE
Cannot complete packaging tutorial - Mysql repo signatures not signed

### ISSUE THREAD

**Issue by spollard** [sandstorm-io/vagrant-spk#321]
I was just running through the packaging tutorial (https://docs.sandstorm.io/en/latest/vagrant-spk/packaging-tutorial) and ran into an issue. When I run `vagrant-spk vm up` at this step (https://docs.sandstorm.io/en/latest/vagrant-spk/packaging-tutorial/#start-a-virtual-linux-machine-containing-sandstorm), I get a non-zero exit status and this message from apt:
```    
    default: Reading package lists...
    default: W: GPG error: http://repo.mysql.com/apt/debian buster InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 467B942D3A79BD29
    default: E: The repository 'http://repo.mysql.com/apt/debian buster InRelease' is not signed.
```

I'm using 
ubuntu 20.04
vagrant-spk v1.1.1
vagrant 2.2.19
Virtualbox 6.1.26_Ubuntu r145957

**Comment by ocdtrekkie** [comment]
I transferred this over to the vagrant-spk repo, because it pertains solely to a vagrant-spk stack!

I suspect https://github.com/sandstorm-io/vagrant-spk/blob/master/stacks/lemp/setup.sh#L10-L12 has bitrot somehow.

**Comment by ocdtrekkie** [comment]
So here's the relevant useful links: https://dev.mysql.com/doc/mysql-apt-repo-quick-guide/en/#repo-qg-apt-repo-manual-setup which describes a key rotation between 8.0.27 and 8.0.28. My guess is the rotation is also true for patch releases of 5.7.

We could change the command to what's described in the article, or I suspect this would also work: https://repo.mysql.com/RPM-GPG-KEY-mysql-2022
