### ISSUE TITLE
Sandstorm doesn't restart next "vm up"

### ISSUE THREAD

**Issue by ocdtrekkie** [sandstorm-io/vagrant-spk#336]
I've been noticing an annoying behavior since I started using bullseye images: Sometimes a VM I have worked on will appear to "not work" after I halt and up it, so often between dev sessions I would vm destroy, and start fresh. I've figured out the reason why is Sandstorm sometimes just does not appear to start, as I can vagrant-spk vm ssh, sudo sandstorm start, and then everything works fine in my dev VM again.

**Comment by ocdtrekkie** [comment]
@zenhack Any chance you've ever seen this behavior? It feels unlikely to me to be specific to running a Windows host, but it's presumably plausible, I guess? Every single time I revisit an existing vagrant-spk vm, I have to ssh and sandstorm start, and it definitely didn't do it before.

**Comment by zenhack** [comment]
I haven't, though I just looked and it looks like I haven't actually upgraded to bullseye on any of the vagrant-spk apps I maintain... I'll let you know when I find the time to actually try it.

**Comment by ocdtrekkie** [comment]
I thought it could be Windows or Bullseye-based, but when working on WordPress, I had the same issues. And that was using Buster on a Debian host.

**Comment by ocdtrekkie** [comment]
I am sort of wondering if @troyjfarrell fixed this in #326 and I just didn't notice because the Windows release didn't have the latest changes. I am going to close it now that 1.1.2 is out, and I'll reopen it if I see it again.
