### ISSUE TITLE
Upgrade to Debian Bookworm

### ISSUE THREAD

**Issue by ocdtrekkie** [sandstorm-io/vagrant-spk#343]
We need upgrade our default machine and our stacks to Debian Bookworm.

This entails ensuring especially that our stacks are updated as necessary for the correct versions of everything that refers to the distribution, and we need to ensure the PHP and Python test apps still work correctly.

https://github.com/sandstorm-io/php-app-to-package-for-sandstorm
https://github.com/sandstorm-io/python-app-to-package-for-sandstorm

Our last upgrade, to Bullseye, was here: #331

**Comment by kokobhara** [comment]
Hi @ocdtrekkie , I'm new to open-source and from the looks of it, this looks doable. Can I take a shot at this?

**Comment by ocdtrekkie** [comment]
Absolutely. It shouldn't be too different from the example of last time we did it, I usually have to look up a few things like what versions the new Debian release uses... but I'd expect basically changes only where I made changes before.

Then testing it of course. I'd recommend trying out one of the test apps once so you're familiar what the end result should look like, and then we just need to verify they still work after.

I'm happy to point you in the right direction if you have any questions. This is a project I really just... haven't gotten around to doing myself, but I can walk someone through it probably.

**Comment by kokobhara** [comment]
I'll get on it right away. Thanks!

**Comment by kokobhara** [comment]
Hi, I trying to set the project up and after following the steps from [here](https://github.com/sandstorm-io/python-app-to-package-for-sandstorm), I get this error:
```
Calling 'vagrant' 'up' in /Users/kokobhara/Desktop/dev/python-app-to-package-for-sandstorm/.sandstorm
Traceback (most recent call last):
  File "/Users/kokobhara/Desktop/dev/vagrant-spk/vagrant-spk", line 1013, in <module>
    main()
  File "/Users/kokobhara/Desktop/dev/vagrant-spk/vagrant-spk", line 1010, in main
    operation(args)
  File "/Users/kokobhara/Desktop/dev/vagrant-spk/vagrant-spk", line 928, in vm_subcommand
    call_vagrant_command(sandstorm_dir, *args.command_specific_args)
  File "/Users/kokobhara/Desktop/dev/vagrant-spk/vagrant-spk", line 326, in call_vagrant_command
    return subprocess.check_call(command, cwd=sandstorm_dir)
  File "/Users/kokobhara/.pyenv/versions/3.10.13/lib/python3.10/subprocess.py", line 364, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/Users/kokobhara/.pyenv/versions/3.10.13/lib/python3.10/subprocess.py", line 345, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/Users/kokobhara/.pyenv/versions/3.10.13/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Users/kokobhara/.pyenv/versions/3.10.13/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'vagrant'
```
I'm sure I'm configuring the project wrong somewhere. Can you help me out with this?

**Comment by ocdtrekkie** [comment]
Do you have vagrant and virtualbox installed?

This page can has commands to check if each thing you need is installed and links where to get them: https://docs.sandstorm.io/en/latest/vagrant-spk/installation/

It is probably worth me asking what OS you are working from as well.

**Comment by ocdtrekkie** [comment]
(I now realize this repo's readme doesn't actually indicate you'll need Vagrant and Virtualbox at all or point you to the installation instructions which do... and that's honestly probably a separate easy PR.)

**Comment by kokobhara** [comment]
At the moment, I'm using OS X Ventura

**Comment by ocdtrekkie** [comment]
@kokobhara Okay, that should work pretty well. I use Windows often but the documentation is a little weaker on what to do in that case for a few things. If you are able to install Virtualbox and Vagrant, it the instructions should work. If you run into any difficulties let me know.

**Comment by kokobhara** [comment]
I tried really hard setting up Vagrant on macOS, but the support is really limited using VirtualBox (for M1), and I just can't make it work with the VMWare provider. I tried shifting my set up to my Windows machine (WSL - Ubuntu), but then it gave me errors on the host not being present of DrvFs. I'm reading up whatever I can find on this set of problems, but have basically hit a roadblock.

**Comment by ocdtrekkie** [comment]
Ahhhh, you got an M1. Yeah, unfortunately I know the box we use and is pretty Virtualbox-specific. I've done some vagrant-spk using the Windows install of vagrant-spk outright, but while I got WSL2 installed on the same machine recently, I haven't played with vagrant-spk in WSL yet.

If you wanted to try it with Windows, the big thing is that I don't think our documentation instructs on how to add things to your PATH, and if you're using the Python file to dev on, instead of the EXE we publish (which is very out of date), you likely have to invoke "python vagrant-spk" or something like that every time, since Windows won't treat it as an executable.

**Comment by kokobhara** [comment]
I'm fine with working on Windows. Maybe a couple of pointers, as to what changes where (for instance invoking python vagrant-spk in place of vagrant-spk), will help a lot. I'll see what I can manage.

**Comment by kokobhara** [comment]
Okay, so I made it work and started making a couple of changes. What I discovered is that MySQL presents some problems while installing on the distribution, quoting some "unmet dependencies". I checked out the repo [here](http://repo.mysql.com/apt/debian/dists/) and there's no distribution for bookworm at the moment.

**Comment by ocdtrekkie** [comment]
I found this, which at least indicates the "October release" will have it, though I'm annoyed at their speed here, it's been months... https://bugs.mysql.com/bug.php?id=111398

**Comment by ocdtrekkie** [comment]
Based on the dates of previous releases here all being pretty consistent, I'm guessing we have like a week or so until the October release... https://dev.mysql.com/doc/relnotes/mysql/8.0/en/

**Comment by kokobhara** [comment]
I guess we should until next release then. Let me know if there's anything else I can help with.

**Comment by ocdtrekkie** [comment]
As I mentioned above, I definitely would accept a readme PR indicating the Vagrant and Virtualbox requirements and maybe linking to the installation documentation for details. That wasn't obvious to you and I can understand why!

That MySQL release should also happen before the end of Hacktoberfest, but if you make a PR that mirrors the earlier distro upgrade PR linked in the original post that we "expect will work". I will approve it even if we're unable to test it and merge it before the end of the month so you get credit for it.

**Comment by kokobhara** [comment]
I'll see what I can come up with the README PR.
As to the time constraint for Hacktoberfest, I'm not targeting that. I wanted to get involved with open source to grow as a developer, so it's okay even if the release takes longer.

**Comment by ocdtrekkie** [comment]
This should finally be doable! https://dev.mysql.com/doc/relnotes/mysql/8.0/en/news-8-0-35.html

**Comment by kokobhara** [comment]
I'll take a look. Thanks for the heads up.

**Comment by ocdtrekkie** [comment]
@kokobhara Just checking to see if you are still interested in tackling this one. As we are currently working on a bit of a project relaunch (https://sandstorm.org/news/2023-10-23-sandstorm-tempest-and-the-future), I am going to probably need to do it myself soon.

I am fixing our release process tonight (which will release as vagrant-spk 1.1.2), but the full release, vagrant-spk 1.2, will depend on this update.

**Comment by kokobhara** [comment]
Hi @ocdtrekkie , yes I'm yet to start working on this. I had been out travelling and could not pick this up. I'll try to finish this up quickly. Thanks for the heads up.

**Comment by kokobhara** [comment]
I gave it another shot, but I'm running into some 'libssl' issues now. I've put in a lot of effort, but I've got some other stuff on my plate at the moment. I don't want this problem to hold up the next release, so I'm passing it over to you. I'll keep an eye out for any other issues I can help with in Sandstorm. Thanks a lot for your assistance!

**Comment by ocdtrekkie** [comment]
Alright, no problem. Thanks for trying! I'm not sure what that error could be without seeing the full message, but I'm sorry I wasn't able to get you through it.
