### ISSUE TITLE
Add an issie Template

### ISSUE THREAD

**Issue by Vijaykv5** [sandstorm-io/vagrant-spk#345]
Add an issue template, so contributors can directly mention the category issue when they raise the issue

**Comment by Vijaykv5** [comment]
I would love to work on it... Please assign me

**Comment by ocdtrekkie** [comment]
We probably don't have a lot of interest in issue boilerplate for this project. Most issues are kicked open by core community folks to begin with and we don't currently have an rate of issue reporting that justifies additional triage help.
