### ISSUE TITLE
The shell scripts generated by vagrant-spk should be set -eou pipefail

### ISSUE THREAD

**Issue by paulproteus** [sandstorm-io/vagrant-spk#35]
That way, failure will be more clear.

**Comment by zarvox** [comment]
I think you mean `-euo pipefail` - the o and pipefail have to go together.  But +1.

**Comment by zarvox** [comment]
Fixed by f24374e15c7b959b74196e119899951d75a99d2b.

**Comment by paulproteus** [comment]
Yippee!
