### ISSUE TITLE
vagrant-spk up failure

### ISSUE THREAD

**Issue by ndarilek** [sandstorm-io/vagrant-spk#36]
This is with a freshly-created `vagrant-spk setupvm meteor`:

Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'debian/jessie64'...

[KProgress: 20%
[KProgress: 30%
[KProgress: 40%
[KProgress: 90%
[K==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'debian/jessie64' is up to date...
==> default: Setting the name of the VM: sandstorm_default_1437148847579_3526
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 6080 => 6080 (adapter 1)
    default: 22 => 2222 (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection timeout. Retrying...
    default: 
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default: 
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
    default: The guest additions on this VM do not match the installed version of
    default: VirtualBox! In most cases this is fine, but in rare cases it can
    default: prevent things such as shared folders from working properly. If you see
    default: shared folder errors, please make sure the guest additions within the
    default: virtual machine match the version of VirtualBox you have installed on
    default: your host and reload your VM.
    default: 
    default: Guest Additions Version: 4.3.18
    default: VirtualBox Version: 5.0
==> default: Mounting shared folders...
    default: /opt/app => C:/Users/nolan/Projects/Scheduler
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

chown `id -u vagrant`:`id -g vagrant` /opt/app

Stdout from the command:

Stderr from the command:

stdin: is not a tty
chown: changing ownership of ‘/opt/app’: Not a directory
Calling 'vagrant' 'up' in c:\users\nolan\Projects\Scheduler\.sandstorm
Traceback (most recent call last):
  File "c:/users/nolan/appdata/local/bin/vagrant-spk", line 779, in <module>
    main()
  File "c:/users/nolan/appdata/local/bin/vagrant-spk", line 776, in main
    operation(args)
  File "c:/users/nolan/appdata/local/bin/vagrant-spk", line 699, in bring_up_vm
    call_vagrant_command(sandstorm_dir, "up")
  File "c:/users/nolan/appdata/local/bin/vagrant-spk", line 620, in call_vagrant_command
    return subprocess.check_call(command, cwd=sandstorm_dir)
  File "C:\python2\Lib\subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['vagrant', 'up']' returned non-zero exit status 1

The second `vagrant-spk up` works, claiming that VirtualBox is already running. Though I don't know what state it's in; perhaps failure to launch the VM should run halt, and up should always attempt a provision? Or an up that fails to create the VM should halt and destroy so Vagrant won't be in an inconsistent state?

**Comment by paulproteus** [comment]
Hi Nolan,

Thanks for filing this. Let me take a look.

**Comment by paulproteus** [comment]
Hi @ndarilek ,

I'm learning something about VirtualBox + Vagrant, and not yet sure what to do about it. TL;DR, if you uninstall VirtualBox and install version 4.3.x from https://www.virtualbox.org/wiki/Download_Old_Builds_4_3 , you should be in good shape. Let me know if that does the trick.

Also/alternatively, if you do:

```vagrant plugin install vagrant-vbguest```

then edit `.sandstorm/Vagrantfile` to add a few lines per the following snippet:

```
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # We base ourselves off Debian Jessie
  config.vm.box = "debian/jessie64"
  # Configure vbguest appropriately
  config.vm.guest = 'debian'
```

You should be able to proceed.

I need to think about how to make this more robust. I'm glad you filed the issue!

**Comment by ndarilek** [comment]
Cool, thanks for finding a solution, but I'm a bit confused. Is the
implication here that Vagrant 1.7.3/VirtualBox 5.0 does something new
that the SPK doesn't yet account for?

If that's the case, then I may hold off for a fix that works with
1.7.3/5.0. Sandstorm is fun to play with but I could probably do with
one fewer distraction just now. :)

Thanks!

**Comment by paulproteus** [comment]
​The one thing that VirtualBox 5.0 does, which vagrant-spk doesn't account
for, is that it is incompatible with some older "Vagrant base boxes."

In particular, it seems to require a newer version of the "VirtualBox guest
additions" than is used in the base box we're using, so "vboxsf" file
sharing doesn't work without taking some action.


Luckily, I think I know what actions are required. If you can test them,
it'd be nice! If not, I totally understand.

If you follow the steps under "Also/alternatively, if you do..." then it'll
let me know if my ideas work on Windows. If so, I can adjust things to
recommend those steps for Windows and other people using VirtualBox 5.0.

**Comment by ndarilek** [comment]
Ah, sorry, missed that. Anyhow, still getting:

The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

chown `id -u vagrant`:`id -g vagrant` /opt/app

Stdout from the command:



Stderr from the command:

stdin: is not a tty
chown: changing ownership of ???/opt/app???: Not a directory


This is with the plugin installed and the Vagrantfile modified. I don't
see a warning about missing guest additions. Additionally, when I SSH
into the VM, `ls /opt/app` gives "Operation not permitted," even as root.

**Comment by paulproteus** [comment]
Whoa, OK. Looks like I should test on Windows,then!

**Comment by ndarilek** [comment]
Looks like this was an issue with Vagrant 1.7.3, since fixed in 1.7.4. Apologies for the false alarm. I don't see Hashi announcing new releases anywhere, so didn't realize a new point release shipped so quickly after .3.

That said, I am getting a new, probably unrelated failure. Going to investigate whether an issue exists for that before filing.

**Comment by ndarilek** [comment]
Minor issue, it does appear that VirtualBox 5 users still need the
vagrant-vbguest plugin, even with Vagrant 1.7.4. Looks like lots of the
boxes have yet to be updated with new, compatible guest additions.

I tweaked the Vagrantfile with your code addition to hopefully work both
with and without this plugin installed. Maybe the default
vagrant-spk-generated Vagrantfile should be modified as follows so it
works everywhere:

  # We base ourselves off Debian Jessie
  config.vm.box = "debian/jessie64"

  if Vagrant.has_plugin?('vagrant-vbguest') then
    # Configure vbguest appropriately
    config.vm.guest = 'debian'
  end

with a note to install vagrant-vbguest if running VirtualBox 5 in the
README.

With that plus Unix line endings, I'm able to build an SPK for my app
under Windows. `vagrant-spk dev` also works.

**Comment by paulproteus** [comment]
Great. Probably we should inspect the current version of VirtualBox and, if
it starts with "5.", then we should check if the `vbguest` plugin is
installed, and if not, print a loud error message saying people should run

vagrant plugin install vagrant-vbguest



https://stackoverflow.com/questions/19553417/is-it-possible-to-determine-the-virtualbox-version-within-a-vagrant-plugin
gives one way to check the VirtualBox version number from Vagrant.
