### ISSUE TITLE
Shell script error in Meteor stack

### ISSUE THREAD

**Issue by ndarilek** [sandstorm-io/vagrant-spk#38]
Getting the following after:

```
vagrant-spk setupvm meteor
vagrant-spk up
```

    default: Running: inline script
==> default: stdin: is not a tty
==> default: /opt/app/.sandstorm/global-setup.sh: line 2: set: -
: invalid option
==> default: set: usage: set [-abefhkmnptuvxBCHP] [-o option-name] [--] [arg ...]
==> default: /opt/app/.sandstorm/global-setup.sh: line 5: /host-dot-sandstorm/caches/install.sh
: Protocol error
==> default: /opt/app/.sandstorm/global-setup.sh: line 31: syntax error: unexpected end of file
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
Calling 'vagrant' 'up' in c:\users\nolan\Projects\Scheduler\.sandstorm
Traceback (most recent call last):
  File "c:/users/nolan/appdata/local/bin/vagrant-spk", line 779, in <module>
    main()
  File "c:/users/nolan/appdata/local/bin/vagrant-spk", line 776, in main
    operation(args)
  File "c:/users/nolan/appdata/local/bin/vagrant-spk", line 699, in bring_up_vm
    call_vagrant_command(sandstorm_dir, "up")
  File "c:/users/nolan/appdata/local/bin/vagrant-spk", line 620, in call_vagrant_command
    return subprocess.check_call(command, cwd=sandstorm_dir)
  File "C:\python2\Lib\subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['vagrant', 'up']' returned non-zero exit status 1

**Comment by paulproteus** [comment]
I think the problem here is that the bash script, on Windows, uses
different line endings than we are expecting.

Let me take a deeper look at this soonish. Thanks for filing it.

**Comment by ndarilek** [comment]
Ah, yes, that does appear to be it. I ran `file` on the scripts and it
didn't report the Windows newlines, but maybe it doesn't for scripts.
But running dos2unix on them seems to have fixed the problem, at least
in that the VM is now being provisioned.

**Comment by paulproteus** [comment]
Awesome. Let's start with that, and see if you run into any other problems.
I hope you won't, but you're the one actually testing this (which is hugely
helpful -- thank you!).

**Comment by ndarilek** [comment]
It does appear to have provisioned the VM once I converted to Unix-style
line endings.

**Comment by ndarilek** [comment]
A vagrant-spk with the 2 PRs I submitted this morning applied can launch
a Sandstorm dev environment under Windows. Should work on VirtualBox 4,
or on 5 with the vagrant-vbguest plugin installed. I didn't update the
docs to include the need for the plugin, nor did I make the default
Vagrantfile yell if VB5 is installed. I just made the changes described
in my previous issues.

**Comment by zarvox** [comment]
I'm of the understanding you fixed this with 6caeb59824aa6e4e41ddad3ff6d44dd70f25f1a8, so I'm going to close this issue.  Feel free to reopen if this is still affecting you! :)
