### ISSUE TITLE
Purge logfiles in grain packages

### ISSUE THREAD

**Issue by JamborJan** [sandstorm-io/vagrant-spk#42]
I realized that we get some pretty big log files in grains. I found that when looking for some information about crashing apps. So I know that log files are useful but should be purged rather quickly.

So for example we have in ```data/log/nginx``` the access log which is getting bigger and bigger. I have only in one grain I am using on my own already 2MB (Logs from March 23rd 2015 until today).

Guessing mode: 
- I guess this is something which needs to be set in the environment when packaging the app
- So I guess this needs to be done in ```vagrant-spk``` rather than sandstorm
- But I guess that I can guess wrong ...

JJ

**Comment by paulproteus** [comment]
I think the thing to do is:

* Configure nginx to not store access logs at all, or at least store them in `/tmp`

* Configure nginx to route error logs to the grain log

As for existing packages, you might as well add

`rm -rf /var/log/nginx`

to `launcher.sh` I suppose!

**Comment by JamborJan** [comment]
Thats basically right for nginx. I think thats not enough. What if I build an app where another component is logging a lot of stuff. I guess we should describe in the vagrant-spk docs that people packaging the app should download a grains backup it after having tested the app and check what log files are inside. For all these logfiles a garbage collector needs to be implemented to avoid that the grains get bigger and bigger.

Garbage collectors or avoiders can be:
- write log to sandstorm log (avoider, don't know how that works :-) ).
- delete entire logfile (maybe a bit too much)
- keep only the last 5 lines of the log with ```tail -5 /var/log/nginx/access.log /var/log/nginx/access.log```

Could tell me how to write something in the sandstorm log?

I can send a PR to vagrant-spk with some default files which get reduced to the last 5 lines in ```launch.sh```.

**Comment by JamborJan** [comment]
I have created and tested a more generic solution for ```*.log``` files in ```/var/log```. I am using ```tail```for that.
