### ISSUE TITLE
Meteor platform stack: console.log() seems to disappear

### ISSUE THREAD

**Issue by paulproteus** [sandstorm-io/vagrant-spk#44]
@ndarilek writes about this problem here: https://groups.google.com/forum/#!topic/sandstorm-dev/M41u_K8iAgA

To copy & paste:

> The last things I see on my vagrant-spk dev console are:

```
source-map-support@0.2.8 node_modules/source-map-support
â""â"?â"? source-map@0.1.32 (amdefine@0.1.0)
App is now available from Sandstorm server. Ctrl+C to disconnect.
WriteResult({ "nInserted" : 1 })
```

> This is followed by the shutdown message when I terminate the app.
>
> At the top of server/users.ls I have:

```
console.log("Running")

Meteor.publish "users", ->
  console.log("Subscribing")
  ...
```
> I'd expect to see "Running"/"Subscribing" shortly after I'm told the app
> is running.
>
> Thanks.

**Comment by kentonv** [comment]
Click the wrench icon in the top bar to see debug logs.

**Comment by paulproteus** [comment]
Of course. I'll close this for now and work on one-day updating the docs.
