### ISSUE TITLE
Restoring grain backups in vagrant-spk dev mode

### ISSUE THREAD

**Issue by JamborJan** [sandstorm-io/vagrant-spk#48]
During tests for the Paperwork package update I realized that it is not possible to upload an grain backup to test the update process.

## Desired behavior
It should be possible to run a new version of an app in ```vagrant-spk dev```mode and to upload grain backups to test the migration process.

## Current behavior
When uploading a backup file the error message ```Restore failed: 200 App id for uploaded grain not installed: App Id: ``` is shown. The mentioned App Id is exactly the one which is running in dev mode in the background.

![bildschirmfoto_2015-07-28_um_21_01_05](https://cloud.githubusercontent.com/assets/7508960/8940763/1f3c797c-355b-11e5-81e2-c9b6c25b481c.png)

## Current workaround
A time consuming work around at the moment is:
- Upload or install an older version of the app via upload or market
- Upload the backup of the app
- Uninstall the app again but keep the grain
- Run the app in ```vagrant-spk dev``` mode
- Now you can use the backup grain for testing

**Comment by paulproteus** [comment]
Unless it's a secret app, you don't need to blank out the app ID.

But this is interesting. It seems like a bug in Sandstorm, not in vagrant-spk. I'll try to look into it on Friday or sooner and see what is going on.

**Comment by paulproteus** [comment]
@JamborJan I'm taking a look at this now. Thanks for filing it.

**Comment by JamborJan** [comment]
Cool thanks. It will make testing a lot easier. Database migration test is driving me nuts. Change, build, upload, fail, again ...

**Comment by paulproteus** [comment]
OK! I can reproduce this.

FWIW it's not a `vagrant-spk` bug; it's indeed a Sandstorm bug. Fixing. Thanks @JamborJan ! I'm going to close this bug in favor of https://github.com/sandstorm-io/sandstorm/issues/651
