### ISSUE TITLE
Provide more useful --help

### ISSUE THREAD

**Issue by paulproteus** [sandstorm-io/vagrant-spk#53]
@pwais just did `wipe` and thought he was going to remove his VM but actually removed his scripts. Apparently it's _mostly_ OK this time, but anyway he would like more `--help`!

**Comment by pwais** [comment]
Yep, I'm a doofus.  "Wipe" sounded like "wipe the VM" not "wipe the current directory" to me, and "destroy" sounded more like "destroy the directory" to me. I should have just read the code X_X .

Don't mean to toot my own horn, but here's an example (off the top of my head) of using OptionParser for better `--help` text: https://gist.github.com/pwais/b8975650fa39a7750d43   Though I'm not sure if you're looking to target Python versions that don't have OptionParser.

**Comment by paulproteus** [comment]
You're not a doofus. Thanks for showing me the issues you have been having
so we can continue to make things better.

**Comment by paulproteus** [comment]
I believe that #71 closes this. Thanks @pwais for working on it! (And we removed the pain-inducing `wipe`!)
