### ISSUE TITLE
Provide a way to "enter" a running grain

### ISSUE THREAD

**Issue by paulproteus** [sandstorm-io/vagrant-spk#56]
As an app developer, it would be nice to be able to get a shell inside a running grain to figure out why something is acting the way it's acting.

The standard recommendation is to run:

```
vagrant-spk ssh
cd /opt/app/.sandstorm
sudo nsenter --target $(pidof sandstorm-http-bridge) --wd --mount --net --ipc --uts --pid
```

This issue tracks the creation of a `vagrant-spk` command (e.g. `vagrant-spk entergrain {{grainid}}`) to achieve that.

Separately, it would be nice if doing so would not grow the `sandstorm-files.list`. Since (I believe) that requires cooperation from `spk`, I also filed https://github.com/sandstorm-io/sandstorm/issues/669

**Comment by JamborJan** [comment]
What is the status on that now or in other words: what do you expect from the community? I have been using two things @zarvox told me:

First connecting to a mysql database inside a grain like this:
```
vagrant-spk ssh
sudo -i
mysql -u root --socket
/opt/sandstorm/var/sandstorm/grains/$YOUR_GRAIN_ID/sandbox/run/mysqld/mysqld.sock
```
As I have been working on mysql based apps this was super useful.

And also:
```
cd git/vagrant-spk/
git pull
git checkout nsenter-devgrain
cd git/your-work-in-progress-package
# make sure sandstorm in that VM is running a single grain
vagrant-spk devjoin
```
I only used this once or so as I rather needed access to the database to check things. 

I guess you are planning to build a wrap around that which is valid for everything: access logs in the grain, data and so on.

There is one question I have to clarify for me: what about things like tools for debugging. For example you don't necessarily need a mysql-cli installed to have a running grain e.g. when php-mysql does everything. But to access the database with an client application via ```vagrant-spk entergrain {{grainid}}``` I could use my local installed mysql client no matter if I have a Windows, Mac OS X or Linux machine. Did I get this right?

**Comment by ndarilek** [comment]
Is there any way to enter the grain as the Sandstorm UID/GID? I tried passing `-U 998 -G 998` to the nsenter command line above but am always dropped in as root. 998 is the UID/GID of sandstorm on my VM. I'm trying to diagnose some permissions problems, so being able to pop in as root, change a permission, pop in as sandstorm and run whatever failed would be helpful.

**Comment by kentonv** [comment]
@ndarilek The grain runs in a UID namespace where the Sandstorm UID has been remapped to 1000 and all other UIDs are not mapped at all. I'm surprised you are able to "be root" when you enter it. Note also that the package files as seen inside the grain are on a read-only mount, so even if you have root privileges, you won't be able to modify them.

**Comment by ndarilek** [comment]
I may have been premature, I got a `# ` as the shell prompt which I 
typically associate with root access, but that might just have been the 
generic /bin/sh or whatever comes up by default. Also, whoami and other 
commands didn't work so I couldn't be sure what my uid was. I did think 
I saw uid=0 at some point, but I'm debugging so many issues so it's 
possible I misremembered or lost track. :)

**Comment by zarvox** [comment]
The `nsenter` command provided above does not enter the user namespace of the grain.  You might need to add `--user`?

**Comment by mitar** [comment]
At least on my system (default) paths are different?

Also, I don't have `nsenter` (Ubuntu 14.04 LTS).

**Comment by paulproteus** [comment]
For those who are curious about this, and implementation details:

- `nsenter` is only available in new-ish versions of `util-linux.

- The `sudo nsenter --target $(pidof sandstorm-http-bridge) --wd --mount --net --ipc --uts --pid` command, if you run it as root, will indeed make you UID 0 within the filesystem namespace of the grain. Ubuntu 14.04's util-linux is too old to have this.

- The `sudo nsenter --target $(pidof sandstorm-http-bridge) --wd --mount --net --ipc --uts --pid --user --setuid 1000 --setgid 1000 /bin/bash` would work properly to make you UID 1000. UID 1000 is what the grain runs as, so that's good. However, this doesn't work with the version of `nsenter` within `util-linux` in Debian jessie, which is what `vagrant-spk` uses by default.

- Therefore, I wrote a small Rust program to do all the needed syscalls. That's part of #165.

**Comment by Xqua** [comment]
Any chance someone could give me pointers to enter non dev apps ?

Bascially I am trying to access the databases of different grains (Rocket chat Wekan etc) to pull the activity and put them in a database to do some analysis of user interactions etc. 

I've looked at Vagrant-spk but only found ways to enter a dev app or to package an app. 
What about already packaged and running apps ?

**Comment by zarvox** [comment]
@Xqua We don't really provide tools for that use case, but you have a couple of options:

* take a backup of the grains by clicking the "Download backup" button with the down-arrow icon, and use mongo to examine their storage offline.
* If you're self-hosting Sandstorm, look in `/opt/sandstorm/var/sandstorm/grains/<grainId>/sandbox/` and examine the grain storage live.

**Comment by Xqua** [comment]
Hum ok, so with MongoDB being a little bit of a pain now (mongodump does not support dbpath anymore) and the lock being present as the app is running. The easiest way is to connect to the mongo instance running in sandstorm.
But this seems to be impossible right ?

**Comment by kentonv** [comment]
Yeah, basically what you need is for each app to provide you with an API that returns the data you want. If the app doesn't provide an API, Sandstorm by design doesn't make it easy to reach in to the app's internals to rip the data out.

That said, it sounds like the data you are interested in is a stream of activity events. As it turns out, we recently introduced an "activity events" API into Sandstorm, and we have been updating apps to publish their events to that API. Eventually, this will be used to maintain an activity log in Sandstorm's own database, outside of the apps. Possibly you would be able to query that.

Unfortunately, at present we do not yet store the activity as a log. Right now, we're only using the API to generate notifications.

**Comment by Xqua** [comment]
@kentonv Yes that would be very interesting indeed ! 
Well for now, I'm basically Rsyncing the databases of the gain out, as well as the sandstorm MongoDB.

Parsing the sandstorm DB for metadata about the grains ID app name and users, and then opening each database outside of the sandstorm vault. 

It works, but it's not very clean and I do this on a cron based system, which is far from perfect (as it is not asynchronous). 

The advantage is that I am maintaining a backup of the DBs though.

**Comment by zenhack** [comment]
I think this was solved a while ago -- there's now an `enter-grain` subcommand.

**Comment by kentonv** [comment]
Indeed!
