### ISSUE TITLE
UI Issue: without an account, asked to "sandstorm admin-token", sandstorm not installed. 

### ISSUE THREAD

**Issue by datakid** [sandstorm-io/vagrant-spk#68]
After the "vagrant-spk up" step, when surfing to http://local.sandstorm.io:6080/, if a user account doesn't exist, there is an error message along the lines of "No users exist, run `sandstorm admin-token` to login".

When run the command returns: "sandstorm: command not found" 

Actual action to be taken is:

in top right corner, drop down "Sign In" and choose "dev account"

**Comment by datakid** [comment]
Addendum: on Ubuntu 14.04.03 LTS up-to-date, using vagrant 1.7.4, Oracle VM VirtualBox Manager 5.0.4, vagrant-spk (commit 7f29d1f)

**Comment by zarvox** [comment]
sandstorm-io/sandstorm#891, once merged, will simply present you with the standard login page (which includes dev accounts) rather than the `sandstorm admin-token` suggestion, which I think would have prevented your confusion.

Thanks for pointing this one out!

**Comment by paulproteus** [comment]
This is now fixed, per my manual testing a moment ago. Thanks to @datakid for filing the bug!
