### ISSUE TITLE
Show icons when running vagrant-spk dev

### ISSUE THREAD

**Issue by rchrd2** [sandstorm-io/vagrant-spk#72]
I've found that `vagrant-spk dev` doesn't show the icons. This would be helpful for prototyping how the icons look in the actual shell. It **does** show on the "New" page, but it doesn't show anywhere else. See screenshots:

![screen shot 2015-10-06 at 1 19 22 am](https://cloud.githubusercontent.com/assets/182479/10303402/4f1056fc-6bc8-11e5-9dde-49af4a998cca.png)
![screen shot 2015-10-06 at 1 16 54 am](https://cloud.githubusercontent.com/assets/182479/10303352/1ab74834-6bc8-11e5-97fe-106755416443.png)
![screen shot 2015-10-06 at 1 17 15 am](https://cloud.githubusercontent.com/assets/182479/10303353/1ad8cc8e-6bc8-11e5-8a03-54c40a8fd044.png)

**Comment by paulproteus** [comment]
Yippee.​
