### ISSUE TITLE
Use *.localhost not *.local.sandstorm.io

### ISSUE THREAD

**Issue by paulproteus** [sandstorm-io/vagrant-spk#73]
It'd be nice to not have to explain-away what `local.sandstorm.io` is.

**Comment by zarvox** [comment]
I thought this only worked on certain browsers and platforms.

**Comment by paulproteus** [comment]
Yeah. I am hoping to use this issue to figure out what platforms/browsers
it does/doesn't work on, then either close WONTFIX or resolve this issue.

**Comment by ocdtrekkie** [comment]
We should begin to transition this over. Kenton suggested support for this is much wider now. So we'll test this, ensure it works on Firefox and Chrome at minimum, and then start to transition documentation and in-app instructions.

**Comment by ocdtrekkie** [comment]
On my Windows machine, I booted up a fresh vagrant-spk VM, SSH'ed in, edited both BASE_URL and WILDCARD_HOST to use localhost instead of local.sandstorm.io and then restarted the Sandstorm service. Using Firefox 74.0.1, the grain frame just stuck on loading when I tried to open a grain this way.

**Comment by ocdtrekkie** [comment]
I can confirm it works in Chromium-based Edge, so it's not a Windows-specific malady but a Firefox-specific one. So this change would be fine for Chromium-based users, but probably broke for everyone not wanting to join the embrace of Google.

I am unsure if there is a good search term for *.localhost support upon which we could investigate if Firefox ever intends to implement this. I would be opposed to the change if they are not, as local.sandstorm.io "just works".

**Comment by zenhack** [comment]
The other thing to bear in mind is, even if browsers start supporting this universally, developers working on apps that generate offer iframes may run into problems if they try to use the tokens from things other than browsers.

**Comment by ocdtrekkie** [comment]
Do we want to just say we aren't going to do this then? How do you feel about it? (It's actually not a vagrant-spk change, as we're just using Sandstorm's dev install flag.)

**Comment by zenhack** [comment]
That's my inclination; Using *.localhost would be nice if everything
supported it, but i don't see a good out for us otherwise.

Quoting Jacob Weisz (2020-04-06 15:51:42)

>    Do we want to just say we aren't going to do this then? How do you feel
>    about it? (It's actually not a vagrant-spk change, as we're just using
>    Sandstorm's dev install flag.)

**Comment by ocdtrekkie** [comment]
As discussed in 2015 then, going to treat this as a wontfix.
