### ISSUE TITLE
Move docs to vagrant-spk.readthedocs.org, and start using version numbers

### ISSUE THREAD

**Issue by paulproteus** [sandstorm-io/vagrant-spk#9]
My goal here is that we should start publishing vagrant-spk "versions", so that people can make sure to get the docs for the version they're using.

**Comment by ocdtrekkie** [comment]
We do now push vagrant-spk versions, but I am going to close this because we currently host vagrant-spk docs via Sandstorm, which I would vastly prefer over publishing docs to an external service.
