### ISSUE TITLE
Meteor platform stack: MongoDB migration problems

### ISSUE THREAD

**Issue by paulproteus** [sandstorm-io/vagrant-spk#93]
I'm upgrading meteor-todos from an older meteor-spk (from February 2015) to the latest vagrant-spk Meteor stack.

New instances of the app launch fine.

But when I launch existing instances, I get this in the logs:

```
Starting migration to WiredTiger storage engine...
launching niscud
note: noprealloc may hurt performance in many applications
about to fork child process, waiting until server is ready for connections.
forked process: 6
all output going to: /var/mongo.log
log file [/var/mongo.log] exists; copied to temporary file [/var/mongo.log.2015-10-29T17-56-56]
child process started successfully, parent exiting
** Starting Mongo...
2015-10-29T17:56:57.037+0000 I STORAGE  Engine custom option: log=(prealloc=false,file_max=200KB)
about to fork child process, waiting until server is ready for connections.
forked process: 18
child process started successfully, parent exiting
error: MongoError: connect ECONNREFUSED
```

Code available here: https://github.com/paulproteus/meteor-todos-sandstorm (use the master branch; use `vagrant-spk`)

SPK & backup to reproduce the problem available here: https://oasis.sandstorm.io/shared/eNt4Jll1XyOUPjnvQstLGGEF1oPUDfmRSaX-LO7RPJP

I can look into this soonish but I figure @dwrensha if you know what's going on quickly, then feel free to suggest a fix.

**Comment by dwrensha** [comment]
Seems to work for me

```
sandstorm/supervisor.c++:1144: warning: ip_tables kernel module not loaded; cannot set up transparent network forwarding.
Starting migration to WiredTiger storage engine...
launching niscud
note: noprealloc may hurt performance in many applications
about to fork child process, waiting until server is ready for connections.
forked process: 6
all output going to: /var/mongo.log
log file [/var/mongo.log] exists; copied to temporary file [/var/mongo.log.2015-10-29T18-11-48]
child process started successfully, parent exiting
** Starting Mongo...
2015-10-29T18:11:48.137+0000 I STORAGE  Engine custom option: log=(prealloc=false,file_max=200KB)
about to fork child process, waiting until server is ready for connections.
forked process: 18
child process started successfully, parent exiting
collection: system.indexes
collection: users
collection: lists
** Starting Meteor...
{ type: 'sandstorm', userId: 'At4Bdji5gPRma7J9T' }
```

**Comment by paulproteus** [comment]
Huh, interesting...

I'll see what I'm doing differently/wrong.

**Comment by jparyani** [comment]
This problem is reproducable on oasis for me, but weirdly it works fine on my local box. @dwrensha, can you try it on oasis?

**Comment by dwrensha** [comment]
I'm able to reproduce this on Oasis and Testrock. I'm still not sure what's going on, but it did cause me to find a bug in the migration script: https://github.com/sandstorm-io/meteor-spk/pull/11

**Comment by dwrensha** [comment]
I had been under the impression that `mongod --fork` would only return after the server had started listening for connections. Apparently that's not the case: https://jira.mongodb.org/browse/SERVER-16292

**Comment by zarvox** [comment]
Amazing.  Is writing the pidfile an indication of readiness?  Binding and listening on the port?  Or does mongo just have no way to signal readiness, period?

**Comment by dwrensha** [comment]
You can read the log and wait for a string like "[initandlisten] waiting for connections on port 8001".
:(

Maybe the best thing for us to do is to retry connecting once, then give up.

**Comment by dwrensha** [comment]
@paulproteus: Does the problem go away after applying https://github.com/sandstorm-io/meteor-spk/pull/13?

**Comment by zarvox** [comment]
I'm guessing when this is done sorting out, we'll want a meteor-spk release and a vagrant-spk bump to use that version, and possibly PRs against meteor-spk-powered apps like wekan to use the newer version?

**Comment by kentonv** [comment]
meteor-spk-0.1.8 is out with the fixes.

**Comment by paulproteus** [comment]
Will test the corresponding update in vagrant-spk now​

**Comment by paulproteus** [comment]
Fixed and I just published Simple Todos this way.

I do have a weird issue, though, where I have:

```
Meteor.startup(function() {
// ... other stuff
    if (Lists.find().count() === 0) {
        Lists.insert({
          name: "My List",
          incompleteCount: 0});
      }
    }
});
```

and this triggers every single time I click **Restart Grain**.

No idea why, since presumably the first time it runs, it makes a `List`. Anyway. +1 thanks @dwrensha

**Comment by dwrensha** [comment]
> and this triggers every single time I click Restart Grain.

Is this on the client side? Maybe you need to wait until Lists's [subscription is `ready()`](http://docs.meteor.com/#/full/meteor_subscribe)?

**Comment by paulproteus** [comment]
Weirdly it's not; it's in server/bootstrap.js
